### ISSUE TITLE
The documentation examples do not include namespaces

### ISSUE THREAD

**Issue by romannowicki** [PHP-DI/PHP-DI#237]
in Configuring the container section the example given is invalid

```php
$container = ContainerBuilder::buildDevContainer();
```

it should be

```php
$container = \DI\ContainerBuilder::buildDevContainer();
```

**Comment by mnapoli** [comment]
Yes this is consistent with most of the documentation as I assume people know about namespace and can handle this.

But maybe the namespace could be included, at least in the getting started and maybe at the start of each documentation so that people landing on the website are not confused.

Feel free to submit a pull request if you feel up to it.

**Comment by mnapoli** [comment]
This was fixed in the new website.
