### ISSUE TITLE
Didn't get it in your example

### ISSUE THREAD

**Issue by JurekRaben** [PHP-DI/PHP-DI#255]
Hey guys, in your example here: http://php-di.org/doc/understanding-di.html

I still didn't get the benefit of the dependency injection approach. Instead I would simply do the classes like this:

    class StoreService {
        private $geolocationService;

        public function StoreService($service) {
            $this->geolocationService = $service;
        }

        public function getStoreCoordinates($store) {
            return $this->geolocationService->getCoordinatesFromAddress($store->getAddress());
        }
    }

And the call:

    $storeService = new StoreService(new GoogleMaps());

Here I also do not need to change store service itself and only have to change one word, if I want to change the service.... I also would say my example is even more easy to read later.... Maybe the example is not so well chosen? Is there a better example to be convinced? Thanks.

**Comment by mnapoli** [comment]
Maybe the documentation can be improved indeed.

> I still didn't get the benefit of the dependency injection approach.

Do you mean "I still didn't get the benefit of the dependency injection *container* approach" instead?

Because the example you posted is using dependency injection. The container is useful when your application gets bigger and you want to avoid duplicating code like `new StoreService(new GoogleMaps())` all over the place. "I only have to change one word" can then become "I have to change it everywhere in the codebase.

**Comment by mnapoli** [comment]
Hopefully the new website and documentation improved things, closing.
