### ISSUE TITLE
call() not automatically injecting from container

### ISSUE THREAD

**Issue by AydinHassan** [PHP-DI/PHP-DI#278]
```php
$container->set('test', 'lol');

//From the docs - works
$container->call(function ($test) {
    echo $test;
}, ['test' => $container->get('test')]);

//Does not work
$container->call(function($test) {
   echo $test;
});
```

Results in
```php
Fatal error: Uncaught exception 'DI\Definition\Exception\DefinitionException' with message 'The parameter 'test' in /Users/Aydin/projects/jh-deploy/vendor/mnapoli/php-di/src/DI/Definition/Exception/DefinitionException.php on line 24
```

Is it possible to make this behaviour work? (Eg. The container should resolve `$test` to the container entry `test`) I sort of expect that to work based on how other parts of the container works. In my case the `callable` is user-supplied and I want to make anything in the container available without having to explicitly define everything as available via the second argument to `call`

Is this possible?

I am using `4.x` at the minute!

Thanks!

**Comment by mnapoli** [comment]
Hi, this is the expected behavior: PHP-DI never uses parameter names to guess the injections. This is something that has been discussed a little already and basically sums up to that:

- either we use parameter names to guess injections everywhere, but it raises several problems:
    - it wouldn't allow to inject everything (e.g. what if the container entry name contains `.` or `-`, which happens often in medium-big applications or when combined with Symfony/Slim/Silex/…)
    - it would be yet another magical feature and could be surprising for people not expecting that - autowiring based on type-hinting is common (Laravel, …) but not for parameter names
    - it would add yet another layer of complexity for users: "what is the priority between type-hints and parameter names?", …
- either we never use parameter names to be consistent and avoid surprises (current status)

The solution I'd rather implement is going the AngularJS way since it works for everything, and developers are more likely to be familiar with it. See #239

**Comment by mnapoli** [comment]
FYI that works too:

```php
$container->call(function ($test) {
    echo $test;
}, ['test' => \DI\get('test')]);
```

I know it's not a direct solution to your problem, but it's just to let you know.

**Comment by AydinHassan** [comment]
Thanks for the detailed reply, guess I will just announce specific services. It is probably the better approach anyway just a bit more verbose. I'll clise this for now
