### ISSUE TITLE
BC break with version 4.4.9: DI\ContainerInterface

### ISSUE THREAD

**Issue by DHager** [PHP-DI/PHP-DI#287]
It seems `DI\ContainerInterface` was removed between 4.4.8 and 4.4.9, in commit 639a3aa4f86cf0a09878291acb468648668e040e.

If this is intentional, then shouldn't the version be tagged 4.5.x instead? If it was unintentional, it may be worth checking whether any other changes leaked backwards from the 5.0 branch.

**Comment by mnapoli** [comment]
Hi @DHager 

This was caused by another issue, see #286. In short I made the very stupid mistake of tagging 4.4.9 against master (which is 5.0). So the 4.4.9 release should be ignored completely.

I have released 4.4.10 yesterday (which is what 4.4.9 should have been, i.e. tagged against the 4.x branch), so Composer should install it (if you run `composer update php-di/php-di`).

Sorry for the mistake!

**Comment by mnapoli** [comment]
By the way I don't know if it would make things worse if I removed the 4.4.9 tag, so I'll leave it for now and hopefully not too many people will have installed 4.4.9 (and the solution is just to upgrade to the new version). But I can see how it is confusing.
