### ISSUE TITLE
Risky distinction between array and callable (?)

### ISSUE THREAD

**Issue by mindplay-dk** [PHP-DI/PHP-DI#293]
This example from the documentation spooked me:

    'Foo' => ['FooFactory', 'create'],

How does it tell the difference between an array of strings and a callable factory function?

Which gets priority? And why?

This seems pretty risky, and I would have expected something safer, like e.g.:

    'Foo' => \DI\factory(['FooFactory', 'create']),

For that matter, suppose I wanted the actual callable (the actual array) for some reason - if that gets magically resolved and called, what then? I can't do that?

**Comment by mnapoli** [comment]
Hi, could you link to the documentation where this appears?

```
'Foo' => ['FooFactory', 'create'],
```

This should be recognized as a simple PHP array. Only closures should be recognized as factories (especially because of the problems you mention).

So:

- it should not be recognized as a factory
- it should not be part of the documentation

It should be just a documentation error.

**Comment by mindplay-dk** [comment]
*whew* :-)

[here](https://github.com/PHP-DI/PHP-DI/blob/master/doc/php-definitions.md#factories) - second code sample.

**Comment by mnapoli** [comment]
Ahh thanks for the report, the documentation needs to be fixed :)

I confirm that it only works for closures: https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/Source/DefinitionArray.php#L115-L117

If you have time for a PR that's great, else no worries I'll do it tonight or tomorrow.

**Comment by mindplay-dk** [comment]
PR with documentation updates: #295
