### ISSUE TITLE
How I map a same abstract class for various classes?

### ISSUE THREAD

**Issue by marcusmendesmovin** [PHP-DI/PHP-DI#309]
```
return array(
    AbstractClass::class => DI\object(Advertise::class),
    AbstractClass::class => DI\object(Partner::class),
);
```

**Comment by mnapoli** [comment]
This is not possible because PHP-DI wouldn't know which one to inject when `AbstractClass` is type-hinted in a constructor.

If you are in such a scenario, you are better off naming each instance with a more specific name. E.g. if you had 2 database connections:

```php
return [
    'db.products' => ...,
    'db.stock' => ...,
];
```

The downside is that it doesn't work with autowiring. So you have to use either annotations or configure each injection explicitly in configuration (e.g. configure if you want to inject either the product database or the stock database).

**Comment by mnapoli** [comment]
Also please don't do that: https://github.com/PHP-DI/PHP-DI/issues/156#issuecomment-137173000 (post in another thread with plenty of people involved hoping to get an answer faster).
