### ISSUE TITLE
Autowiring and Annotations do not work for `DI\object()` inside arrays

### ISSUE THREAD

**Issue by mopahle** [PHP-DI/PHP-DI#343]
Example code:

``` php
<?php
require 'vendor/autoload.php';

class A {
  public function __construct(B $b) {}
}

class B {
  /**
   * @Inject
   */
  public function test() {
    echo "Autowiring and Annotations work.";
  }
}

$builder=new DI\ContainerBuilder();
$builder->useAnnotations(true);
$builder->addDefinitions([
  'test'=>[DI\object(A::class)]
]);
$container=$builder->build();

try {
  $container->get('test');
}
catch (Exception $e)
{
  echo $e->getMessage();
}
```

Executing the code above gives the following output: 

```
Error while resolving test[0]. Entry  cannot be resolved: The parameter 'b' of A::__construct has no value defined or guessable
Full definition:
Object (
    class = A
    scope = singleton
    lazy = false
)
```

changing the definitions to `$builder->addDefinitions(['test'=>DI\object(A::class)]);` works as expected.

**Comment by juliangut** [comment]
Is DI\object inside an array a correct usage? I mean you're already using DI\object to create the resolvable

**Comment by mopahle** [comment]
Having only one item in an array may be not really a usecase. But how would you solve something like this without an array:
```php
$builder->addDefinitions([
  'logappenders'=>[
    DI\object(Logappender1::class),
    DI\object(Logappender2::class),
    DI\object(Logappender3::class),
  ]
])
```
and maybe with a second defintion:
```php
$builder->addDefinitions([
    'logappenders'=>DI\add([
        DI\object(Logappender4::class),
    ])
])
```

**Comment by mnapoli** [comment]
That's weird indeed, thanks for the great bug report. The usage seems valid to me and I think I can see why it's not working… After a very quick look I'm not sure what the best fix would be, I'll try to have a look at it soon.

As a workaround (in the meantime):

```php
[
  'test' => [get(A::class)],
  A::class => object(A::class),
];
```

**Comment by mopahle** [comment]
Thanks for the update. However, the workaround does not work for me (still getting the same error).

**Comment by tuanmh** [comment]
I got the same error here. Any plan to fix it?

**Comment by mnapoli** [comment]
I know what causes the bug (ArrayDefinition doesn't trigger autowiring on sub-definitions) but from what I remember it's not an easy one to fix and I don't have a lot of time available to work on it at the moment (publishing the last Slim bridge should have been 2 weeks ago for example).

For anyone wanting to have a look at it: [ArrayDefinition](https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/ArrayDefinition.php) should me made to implement `HasSubDefinition` based on its items. If an item implements `HasSubDefinition` then it should trigger a sub-definition resolution (i.e. the autowiring). Problem: an array definition could have 0, 1 or many sub-definitions because it can have many items. Also it needs to be done with as little performance impact as possible (though the cache should minimize that).

**Comment by tuanmh** [comment]
Thanks for your quick response & detail guides on this :+1:. I'll see if I can help :)

**Comment by leonbobster** [comment]
Just a hack, sorry if it completely against your vision: https://github.com/PHP-DI/PHP-DI/pull/426/files
Any feedback are welcome ;-)

**Comment by mnapoli** [comment]
Hi everyone, this issue has been indirectly fixed by the replacement of `DI\object()` with `DI\create()` and `DI\autowire()`. The good news too is that since the container can now be compiled (#494) performances will not be affected.
