### ISSUE TITLE
Stance on standardized DI definition / configuration snippets

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#363]
Recently I used PHP-DI to replace some parts of a Zend Framework 1 application:

- [Bisna container](https://github.com/guilhermeblanco/zendframework1-doctrine2), that was used to configure Doctrine ORM and ODM
- Zend Cache Manager, switched to [doctrine/cache](https://github.com/doctrine/cache)

This went quite smooth and it made me think of how to 'standardize' such configurations. 

For example, this definition snippet sets up a MongoDB connection with a default collection:

```php
return array(
    MongoClient::class => object()->constructor(get('setting.mongodb.url'), $options = array()),
    MongoDB::class => object()->constructor(get(MongoClient::class), get('setting.mongodb.database')),
    MongoCollection::class => object()->constructor(get(MongoDB::class), $name = 'DefaultCollection'),
)
```

And this can be used to easily set op Doctrine Caches that use a chained approach and a wildcard approach for ease of use: $container->get('ORMAnnotationCacheProvider'):

```php
return array(
    'chainCachesCollection' => array(
        get(Doctrine\Common\Cache\ArrayCache::class),
        get(Doctrine\Common\Cache\ApcuCache::class),
        get(Doctrine\Common\Cache\MongoDBCache::class),
    ),
    Doctrine\Common\Cache\ArrayCache::class => object()->constructor(),
    Doctrine\Common\Cache\ApcuCache::class => object()->constructor(),
    Doctrine\Common\Cache\MongoDBCache::class => object()->constructor(get(MongoCollection::class)),
    Doctrine\Common\Cache\ChainCache::class => object()->constructor(get('chainCachesCollection')),
    '*CacheProvider' => function (Doctrine\Common\Cache\ChainCache $chainCache, RequestedEntry $e) {
        $chainCache->setNamespace($e->getName());
        return $chainCache;
    },
);
```

Would it be an idea to set up a repository to collect such snippets? It is not 'really' a 'bridge', more an application agnostic configuration... Does https://github.com/container-interop/container-interop intend to develop standardized DI configuration approaches as well?

**Comment by mnapoli** [comment]
Hi! Your issue is right on time :)

- PHP-DI reusable modules (like Symfony bundles): I've started working on [PHP-DI/Kernel](https://github.com/PHP-DI/Kernel): this is a project that is meant to be the core of an application that uses modules built with PHP-DI and Puli -> not stable or documented yet. If you want to see an example of such a module, I've written a [TwigModule](https://github.com/mnapoli/TwigModule)
- container-agnostic reusable modules: this is a very hot topic at the moment, we've been working on that with the FIG and container-interop (see for example [container-configuration-meta](https://github.com/container-interop/fig-standards/blob/container-configuration/proposed/container-configuration-meta.md) and [container-interop/definition-interop](https://github.com/container-interop/definition-interop)), feel free to join the discussions on the FIG mailing list or [on Gitter](gitter.im/container-interop/definition-interop). However this is very far from being usable soon so for now only PHP-DI modules are "realistically useful".

**Comment by holtkamp** [comment]
Aah, nice to see, will keep an eye on it and try to contribute whenever applicable! In the time being will try to gain more practical experience on this interesting topic :+1:

**Comment by holtkamp** [comment]
@mnapoli small follow up, maybe off-topic... As you can see the name of the requested CacheProvider determines the namespace of the cache. It would be nice to store these different namespaces in different MongoCollection as well (making it easy to drop / inspect, etc). However, changing the name of the MongoCollection *after* instantiation is not possible. Do you see a way to influence the $defaultCollection parameter without having to resort to creating extra functionality (factories that assemble the cache)? I consider it a challenge to come up with a "as vanilla and versatile as possible" approach, but after some puzzling I think I have to give up...

**Comment by mnapoli** [comment]
Oh well honestly I haven't played with that cache or MongoCollections at all, I had a quick look but I don't see anything obvious to help out :/

**Comment by holtkamp** [comment]
Puzzled a bit more and came up with [this approach](https://gist.github.com/holtkamp/83555be2e542dca3a11e) which uses the power of wildcards to 'hand over' the namespace down the line to the MongoCollection.

**Comment by mnapoli** [comment]
@holtkamp wow… Might be hard to maintain ;)

**Comment by holtkamp** [comment]
@mnapoli :smile: well, once set up like this, I hope it *reduces* the maintenance effort. Each time I need a new cache, it would just be. 
```php 
$dic->get('XYZPurposeCacheProvider');
```

**Comment by mnapoli** [comment]
For the record we have been working for some time on https://github.com/container-interop/service-provider now, feel free to give it a look. We'll share it on the FIG's mailing list in a few days.

I think this issue can be closed as it's not really part of this project.
