### ISSUE TITLE
Support PSR-6 or PSR-16 caching

### ISSUE THREAD

**Issue by mburtscher** [PHP-DI/PHP-DI#376]
PHP-DI should support PSR-6 compliant caching instead of just Doctrine's cache implementation. This will ease integration in existing cache setups in the future.

_This is even more important since Symfony 3.1 will ship with a PSR-6 compliant cache component._

Further reading:
- [PSR-6 specification](http://www.php-fig.org/psr/psr-6/)
- [Symfony PSR-6 implementation pull-request](https://github.com/symfony/symfony/pull/17408)

**Comment by mnapoli** [comment]
Hi, this is a good suggestion. However I don't want to break BC (for now) for people using Doctrine Cache currently. Maybe there's an adapter that exists or could be written to allow passing a PSR-6 cache into a Doctrine Cache typehint…

Also we'll need to see if PSR-6 gains enough traction to eventually replace Doctrine Cache completely.

**Comment by mburtscher** [comment]
Sure BC should not be broken in minor versions. So this may be seen as a proposal for PHP-DI 6. I've implemented all the necessary changes (as far as I can tell) in my private fork:

https://github.com/mburtscher/PHP-DI/commit/83eefa4eadbef506644402290b24cadd89292ecc

I haven't opened a PR yet.

Doctrine users may use the `cache/doctrine-adapter` and still use PHP-DI 6. There is also a `cache/psr-6-doctrine-bridge` package the other way round but I think the default implementation should stick to PSR-6.

**Comment by mnapoli** [comment]
:+1: that's great for PHP-DI 6. Seeing the diff though that's really showing how PSR-6 is overkill for our simple needs, having to reimplement a `CacheItem` is too bad. (just to be clear this is not related to your implementation)

**Comment by mburtscher** [comment]
It might be an option to use the `CacheItem` implementation from the `cache/adapter-common` package but it would introduce a new dependency for PHP-ID :confused:

https://github.com/php-cache/adapter-common

**Comment by nicolas-grekas** [comment]
FYI, Symfony Cache provides Doctrine interoperability in both ways.
See [DoctrineProvider](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/DoctrineProvider.php) and [DoctrineAdapter](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/DoctrineAdapter.php).

**Comment by mnapoli** [comment]
:+1: thanks @nicolas-grekas 

Also for the record, coming back on what I said:

> having to reimplement a CacheItem is too bad.

I was wrong about that (thx @nicolas-grekas again for the explanations), we simply get "empty" CacheItem instances from the pool (those will be "misses" at first).

We could also wait for PSR-16 (the "simple cache" PSR) because it's more appropriate to the use case here, but who knows how long this is going to take.

**Comment by mburtscher** [comment]
I've updated my branch according to the feedback above. The following changes are included in https://github.com/mburtscher/PHP-DI/commit/33f319ee4c76ecaee011a47bcf4266bb297d8414:

* Migration from Doctrine caching to PSR-6
* Completely drop the `ArrayCache` implementation – one could use the `cache/array-adapter` package
* Add `cache/adapter-common` as dev requirement for unit-testing purposes

**Comment by mnapoli** [comment]
PSR-16 has passed, it's simpler to use than PSR-6 and might be a better fit for PHP-DI. So we have to consider using that too. Here is for example the interface: https://github.com/php-fig/simple-cache

**Comment by sagikazarmark** [comment]
I think PSR-16 could be integrated without breaking BC, which would be great, but the question is whether it makes sense before 6.0. If the caching internals change in PHP-DI, then it wouldn't be such gain having the internals rewritten to PSR-16 as you would have to touch it again, BC breaks anyway, probably even for PSR-16 users. I've seen some issues suggesting performance improvements, so I see a slight chance that some caching related internal stuff will change. I am not sure though, I am not that involved into PHP-DI internal, so if the above is not true, I would say go ahead and add PSR-16 support (with backwards compatible Doctrine support) in 5.x (even with the extra dependency).

Since this issue is quite old, I would be happy to pick this up (if noone else wants to do it) as I am using PHP-DI in [nofw](https://github.com/nofw) and I wouldn't mind replacing doctrine cache with a PSR-[1]6 compliant cache implementation.

**Comment by mnapoli** [comment]
@sagikazarmark I'm trying to clean things up as much as possible. I'd rather avoid supporting 2 caching systems (Doctrine and PSR-16).

Because of that, it means BC break, so it means PHP-DI 6. But v6 is almost finished (https://github.com/PHP-DI/PHP-DI/milestone/19), the caching is the last big thing to do. I also want to let things simmer and try the beta versions before releasing (some ideas might come at the last minute) but it shouldn't be too long.

**Comment by mnapoli** [comment]
@sagikazarmark I've opened a pull request: #469

**Comment by sagikazarmark** [comment]
> I'd rather avoid supporting 2 caching systems (Doctrine and PSR-16).

I guess there are adapters between the two interfaces, so internally you should support one, but it's ok for me if you say it doesn't worth it.

**Comment by mnapoli** [comment]
Yes there are adapters for Doctrine so the migration to PHP-DI 6 will be very easy for users.
