### ISSUE TITLE
How to use injection of primitive values

### ISSUE THREAD

**Issue by amakhrov** [PHP-DI/PHP-DI#378]
Container allows to add primitive values (e.g. strings) to the container: http://php-di.org/doc/php-definitions.html#string-expressions
However, it's not clear how to use those values.
E.g. I have a class:
````
class C1 {
    public function __construct($dbName) {
    }
}
````
and the container config:
````
return [
 'db.name' => 'test'
];
````

How can I instantiate this class and make sure the right db name is passed to it? Do I need to provide any specific annotation to the class' constructor for that?

**Comment by mnapoli** [comment]
Hi! It order to inject these values you have to use configuration, because there is no way for the container to guess which value to inject (contrary to objects where the type-hints can be used).

Have a look at creating [factories](http://php-di.org/doc/php-definitions.html#factories) or defining [object injections](http://php-di.org/doc/php-definitions.html#objects).

Here is an example for your use case:

```php
return [
    'db.name' => 'test',

    C1::class => DI\object()
        ->constructor(DI\get('db.name')),
];
```

You can also use [annotations](http://php-di.org/doc/annotations.html) if you want.

Please have a look at that documentation and tell me if something is missing from it. It should be clear enough so that people can get started on their own. If it's not then I can try to fix it.

**Comment by amakhrov** [comment]
@mnapoli thanks a lot!
````
/**
     * Explicit definition of parameters by their name:
     *
     * @Inject({"param2" = "db.host"})
     */
````
This is something I was looking at - it's definitely present in the docs, but somehow I had missed it.
