### ISSUE TITLE
[idea/proposal]  @Initialize function.

### ISSUE THREAD

**Issue by mmizera** [PHP-DI/PHP-DI#382]
When you injecting service, constructor should be blank - and fields are not injected yet. It would be great to add annotation, which you could point to method, which would be executed right after service is created and injected.

Here is IRL example :

```php

	class SomeDao {


	   /**
	     * 
	     * @var EntityManager
	     */
	    protected $entityManager;

	    protected $repository;

		/**
		 * 
		 * @Initialize
		 */
		public function init() 
		{
			$this->repository = $this->entityManager->getRepository($this->getEntityClassName());
		}
	}
```

Basically, Repository object is constructed via entityManager factory method, so you either 

- write factory for Dao
- write getter for repository, which on first time call perform initialization

(imho) If I can specify init method, which is automatically called, this would greatly reduce need for writting factories.

**Comment by mnapoli** [comment]
An initialization method is usually a constructor. I didn't get why you can't write that in you constructor?

Also that should work:

```php
    class SomeDao {

        /**
         * 
         * @Inject
         */
        public function init() 
        {
            $this->repository = $this->entityManager->getRepository($this->getEntityClassName());
        }
    }
```

**Comment by mmizera** [comment]
Hi

How exactly your code should work ? The only way I see is if @Inject will trigger the method, but I have two problems with it 

- You can not ensure, that init method is called after all other injections are finished - and that was the main purpose of proposed feature
- Also it does not make any sense to trigger the unknown method with Inject annotation if you actually does not perform any injections.

Ok, back to the feature, I'll try to explain it once more. Consider @postConstruct annotation from java (http://www.mkyong.com/spring/spring-postconstruct-and-predestroy-example/)


Usecase for this is 

1. Im pulling some service from container for the first time
2. container make all injections (other services and resources)
3. [this I want] container execute method defined via annotation - purpose is to do some stuffs with injected services and resources, make some other non-di intialization etc. 
4. you get service from container

Also init method will be called only once per service instance retrieval, so for singleton scope once, for prototype scope every time you ask for new service.

**Comment by mnapoli** [comment]
Why not use a constructor? That's exactly what it's for: inject the dependencies in the constructor, and then do some initialization.

You can also use a factory if you really don't want to use a constructor:

```php
function () {
    $service = new MyService($c->get('dependency'));
    $service->setOptionalDependency($c->get('other-dependency'));
    $service->init();
    return $service;
}
```

Setters are only good for optional dependencies, else you make your class coupled to the container you use. For example what happens if a developers instantiate your service manually and doesn't call the correct setters/init methods in the correct order? Then the service is in a broken state.

Init methods, as well as those Java annotations, are definitely an anti-pattern. You can perfectly use that pattern if you want to (use a factory as shown above) but I don't want to add features to PHP-DI that are made for an anti-pattern. Going the other way (constructor injection) is very easy.
