### ISSUE TITLE
[idea/proposal] AOP integration or bridge to php-go

### ISSUE THREAD

**Issue by mmizera** [PHP-DI/PHP-DI#384]
would you consider adding AOP, or make some integration with php-go ? That would be huge, if on service layer 	you could intercept methods via proxy and manipulate, monitor, log, authentify etc. with input/output - you know ... AOP :)

**Comment by mnapoli** [comment]
Hi, please see #230.

I wouldn't be against the idea if someone manages to make it work well, but it would need to be in a separate project so that users can install it only if they want to use it (sort of "php-di - AOP integration" package). So feel free to work on this, if you have something working and documented we could add it to the [PHP-DI organisation](https://github.com/PHP-DI). And if you need help I'm available on Gitter to chat!
