### ISSUE TITLE
How to inject values?

### ISSUE THREAD

**Issue by wojciechmorawski** [PHP-DI/PHP-DI#435]
Hey!
PHP-DI is great :) Thank you so much!
One thing which I can not understand is : how to pass a specific value (let say '5') to the class constructor via dependencies.php definition? 

Could you provide a very simple non-abstract example?

Best!

**Comment by mnapoli** [comment]
Sure, here is an example:

```php
return [
    'Foo' => object()
        ->constructor(5),
];
```

or with a closure:

```php
return [
    'Foo' => function (ContainerInterface $c) {
        return new Foo(5);
    },
];
```

**Comment by wojciechmorawski** [comment]
Thanks :) One more - how to pass non-hardcoded data to constructor using definitions? So

$data = $classA->getDataFromDb();

//create classB($data)
$container->get ... ?

**Comment by mnapoli** [comment]
You have to use `DI\get()`, you can have a look at the documentation: http://php-di.org/doc/php-definitions.html

**Comment by wojciechmorawski** [comment]
Thanks once again :)

Sorry for bothering you but I've got no one to ask - sadly my company doesn't know much about about Solid/Stupid principles :( I think I am missing the point somewhere... PHP-DI works fine for me but there is one problem which I am unable to solve by myself.

Let say I've got sth like this:

    $auth = $db->authorize($requestData);

    if ($auth) {
        $userController = new controller($auth);
        $userController->doSomething();
    }

I've got no idea how to use PHP-DI to create $userController with $auth passed in class constructor.
Your solution - 'You have to use DI\get()' - sees to be beyond my understanding. I can try to create sth like this in dependencies.php 

return [
    Controller::class => DI\object()
        ->constructor( `create DB object and exec authorize function` ),
]  

but then authorization method will be executed multiple times during scritp life time.

Meaby my approach is wrong? Meaby I should pass only objects in constructor and provide data only for function calls? Classes are super immutable then.

    $auth = $db->authorize($requestData);

    if ($auth) {
        $userController = new controller();
        $userController->doSomething($auth);
    }

Please help me powerfull programmer! I am lost and I've got no hope :)

**Comment by mnapoli** [comment]
> I've got no idea how to use PHP-DI to create $userController with $auth passed in class constructor.

That's where you need to use `Container::get()` instead of creating your objects yourself.

```php
$auth = $db->authorize($requestData);

if ($auth) {
    $userController = $container->get('ControllerClass');
    $userController->doSomething();
}
```

I also invite you to re-read the getting started guide, especially this section http://php-di.org/doc/getting-started.html#defining-injections 

You could also have a look at the demo application: https://github.com/PHP-DI/demo (which is mentioned in "Getting started" too).

> but then authorization method will be executed multiple times during scritp life time.

Yes, that's why you need to have the container create the authorization class too. You can put that in the container, and then you can inject it in other classes (http://php-di.org/doc/getting-started.html#defining-injections).

Also read this article: http://php-di.org/doc/understanding-di.html

Have also a look at these slides: http://mnapoli.fr/presentations/di/ (I don't have any video unfortunately).

If you still don't understand where the container can be used and what it should do it's OK but I think it's a bit out of the scope of PHP-DI. I have created a few guides in the docs but they are not perfect, however there are plenty of blogs or tutorials on internet to understand it.

Also it's hard for me to judge whether I should tell "read the doc" of if you have already read it, so please let me know if you have read the docs but some parts are not clear enough? I'm sure there is room for improvements.

**Comment by wojciechmorawski** [comment]
Thanks for fast response :) I am leaving for short holidays now. I'll do all my reading and write you back soon :) Best!!

**Comment by wojciechmorawski** [comment]
I am back :).
I've spent some time learning and now PHP-DI it's much more understandable to me.
I think that the biggest problem with documentation is fact that it was created by senior PHP developer :) So generally speaking it's an advantage but if you are newcomer (like me) who is not fluent with design patterns and super abstract approach to solving problems - it might be tricky to understand. Examples are very short, context (Foo, Bar etc) is changeing very often. Also there are almost no tuts for PHP-DI on the web which is strange. Maybe those facts are connected.

Maybe you can make a reading list for begginers?

I've still got problem with getting value from the class in definition file. I want to make sth like this

`...
    B::class => DI\object()->constructor(
        Di\get(A::class->getId())    
    )
...`

Could you show me how it should be done?

Full example:

`class A {
        
    private $id;    

    public function __contstruct() {
        $this->id = rand();
    }        

    public function getId() {
        return $this->id;
    }
}`


`class B {

    public function __contstruct($id) {
        echo "Id from class A is: " . $id;
    }        
}`

dependencies.php file: 

`return [
    A::class => DI\object()->constructor(),
    B::class => DI\object()->constructor(
        Di\get(A::class->getId())    
    )
];`
