### ISSUE TITLE
What is the role of cache

### ISSUE THREAD

**Issue by shuyabin** [PHP-DI/PHP-DI#453]
![image](https://cloud.githubusercontent.com/assets/14884581/22094970/571706a0-de4c-11e6-8041-44198def28ba.png)

I used the cache, but I didn't see any effect . There is no write in the document

**Comment by mnapoli** [comment]
Hi, have you had a look at the documentation http://php-di.org/doc/performances.html ? The performance difference is not very significant (because containers only take a small time compared to the rest of the application), if it doesn't change anything for you then don't use a cache, it's just simpler.

**Comment by shuyabin** [comment]
Thanks
