### ISSUE TITLE
Adopt a code style standard

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#476]
When looking at the code my hands are itching to apply a code-style fixer like [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to it. 

Is a specific type of style already in use? For the 6.0 version, it might be an idea to adopt one?

This also reminded me of [this blog post](https://www.mollie.com/nl/blog/post/migrating-to-psr-2-at-mollie/)

**Comment by mnapoli** [comment]
PHP-DI follows PSR-2 (except method names in tests), but beyond PSR-2 rules there are some discrepancies in the codebase :)

Currently there is [StyleCI](https://styleci.io/repos/3751713) set up, so each pull request/commit is validated by that tool. However:

- the config doesn't seem to be public, so it's not easy to see what's enforced/required and learn from it
- there doesn't seem to be a way to run the tool locally (to check before sending a pull request)

At work we are using [Coke](https://github.com/M6Web/Coke) which is a thin wrapper around PHP CS and it's really nice because you don't have to play with any options and you can commit the config in the repository. Maybe that could be something to look into. PHP-CS-Fixer too but I've never used it, I have no idea how easy it is to use.

**Comment by mnapoli** [comment]
I got an answer from StyleCI: https://twitter.com/TeamStyleCI/status/854791074132480000

Now I've configured StyleCI to automatically push commits that fix the code style. We can see how it goes.
