### ISSUE TITLE
Get rid of the $containerClass parameter in ContainerBuilder

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#479]
https://github.com/PHP-DI/PHP-DI/blob/6f6b380d3dcda5ff47303d60ecafe9b4c5c127ac/src/DI/ContainerBuilder.php#L99-L99

This is only used for tests, it should be visible for end users.

**Comment by juliangut** [comment]
I don't think this is a good idea. Currently I'm extending \DI\Container to add \ArrayAccess functionality ([here](https://github.com/juliangut/slim-php-di/blob/2.x/src/Container.php)).

If setting containerClass is removed from constructor it should be added as a setter, otherwise using other container than \DI\Container would be impossible

**Comment by mnapoli** [comment]
Oh right I had no idea it was used somewhere else than for tests :)

OK let's keep this parameter then!
