### ISSUE TITLE
Extending object definition with method call caues first method call removal.

### ISSUE THREAD

**Issue by pjedwabny** [PHP-DI/PHP-DI#492]
If I create definition eg
```
MenuBuilder::class => DI\object()
        ->method('registerFactory', DI\get(BoxArtykulyNieprzegapFactory::class))
        ->method('registerFactory', DI\get(BoxAdsFactory::class))
        ->method('registerFactory', DI\get(BoxArtykulySingleFactory::class))
        ->method('registerFactory', DI\get(BoxPytanieFactory::class))
```

and in my another module extend it with

```
MenuBuilder::class => DI\object()
        ->method('registerFactory', DI\get(BanerAnkietaGlihemFactory::class))
```

first module `->method('registerFactory', DI\get(BoxArtykulyNieprzegapFactory::class))` is removed

Problem lies in `\DI\Definition\ObjectDefinition::mergeMethodCalls`.

I think that we should
**add method call to list**
or
**remove entire list with one method call from new definition**
but not override only part of definition

**Comment by mnapoli** [comment]
Hi!

Yes it is supposed to work that way mainly because of autowiring.

This is resolved in v6 (not yet released) by replacing `DI\object()` with much more predictable helpers:

- `DI\create()` completely overrides the previous definition
- `DI\autowire()` allows to explicitly configure the autowired entry

There will be no helper to do exactly what you want to do, but at least it will be very clear and there will be no confusion.

The solution you should use is `DI\decorate()` to add new behavior to the previous definition. Maybe in the future there will be a `DI\extend()` helper specifically for that, but I'm not sure all those scenarios are very common, and I'm not sure a helper like `extend()` will be clearer than `decorate()` so I'm not planning on adding it for now.

Hope that helps, I'll be closing the issue since it's addressed in v6.
