### ISSUE TITLE
Nested autowire does not work

### ISSUE THREAD

**Issue by sagikazarmark** [PHP-DI/PHP-DI#501]
Not sure if it is intended/limitation, nevertheless I couldn't find any mention in the documentation (could be I didn't read it carefully).

Reproduced here: https://github.com/reproduce/php-di/tree/nested_autowire

**Comment by mnapoli** [comment]
Thanks for the report! Yesterday I've worked on #499 which should address exactly that.

I've tagged a new alpha release: https://github.com/PHP-DI/PHP-DI/releases/tag/6.0.0-alpha3 Could you try it out?

**Comment by sagikazarmark** [comment]
Unfortunately it's still the same. The above link contains a script reproducing the problem, the result is the same with 6.0.0-alpha3

**Comment by mnapoli** [comment]
Thanks for the test case, indeed I've managed to reproduce it in #503 and I've updated all tests to cover it properly. I'll try to look into a fix for v6 as I'd like to have all those inconsistencies covered.

**Comment by holtkamp** [comment]
@mnapoli also encountered this. Since the combination of referencing / nested dependencies and autowiring occurs often, this breaks quite some stuff.

**Comment by mnapoli** [comment]
@holtkamp gotcha, I was starting to consider this may be a non critical issue that could way a future version but I think I'll fix it for the 6.0 release.

To explain the problem: I can traverse all the tree of the configuration to check for nested stuff, and when using the compiled container it's not a problem because it's done once at compilation time (never done at runtime afterwards).

But that would slow down the non-compiled container… And I'd like to keep it fast if possible (no reason to slow it down). I think I will either have to find a fast solution, or accept that the non-compiled container will slow down.
