### ISSUE TITLE
Rename `ContainerBuilder::compile()`

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#506]
From https://github.com/PHP-DI/PHP-DI/pull/494#issuecomment-306310081

Suggestions:

- `setCompilationPath($filename)`: I'd like to avoid using setters if possible
- `enableCompilation($filename)`

> > Please note that the file name will also be the name of the generated PHP class. Because of that the filename you specify must also be a valid class name
>
> Wouldn't it be better just to use a single file name (CompiledContainer.php is just perfect) and let the user set the path only? (this plays better with my previous suggestion of setCompilationPath)

@juliangut I'm not sure I remember the whole reasons at the moment but I needed being able to set the file name for tests or scenarios where I wanted multiple containers. In any case I think it's also a good thing to let users choose the path and the file name, it allows to avoid creating a directory just for one file, and it allows more control over that file. Users will need to manage that file specifically for their deployment, some others may want to commit it in the repository. If we ever changed the file name it could have bad consequences, I think it's simpler and saner to let users choose the whole file name instead of forcing their hand.

**Comment by juliangut** [comment]
I'm all in for setters but I see in ContainerBuilder there is no "setAnything..." methods so the setCompilationPath name would feel out of place, so go for `enableCompilation`

About the compilation file name thing, I'm not going to try to push it because I get your last point, just one note on your comment: 

> it allows to avoid creating a directory just for one file

Setting the path in which the fixed-name compiled container file is created does not necessary create a new directory for a file, it is the developer's responsibility to set it wherever he/she wants, setting `/path/name` wouldn't prevent developer from creating a directory solely for this file either

**Comment by juliangut** [comment]
Any one else apart from @sagikazarmark has an opinion on this renaming?

**Comment by sagikazarmark** [comment]
> `enableCompilation`

👍 

What if it accepts two parameters: path and filename, the latter falling back to a default. I can imagine scenarios when people might want to have control over the filename, but if it's a best practice to call it xy, then I would rather tend to zero config or less config if possible.

**Comment by mnapoli** [comment]
👍 that's a very good idea, less to think is better!

**Comment by mnapoli** [comment]
I've opened #509 and I think I have an even simpler solution: customize the class name instead of the file name. That allows to avoid checking that the file name is a valid class name (and all the documentation that goes with it).
