### ISSUE TITLE
Using the dev-master branch there is no DI\object() anymore

### ISSUE THREAD

**Issue by azngeek** [PHP-DI/PHP-DI#513]
It seems like that there is no DI\object() anymore. Could it be that this has been replaced? I am currently working with the dev-master branch. Without refactoring my code which is the last stable branch to use which supports DI\object()?

**Comment by mnapoli** [comment]
Hi there, master is v6, you should not be using master unless you are OK with constantly migrating your code because master is not stable ;)

Why not use a fixed release?

FYI here is the upgrade guide, but it is **not definitive** because, again, master is not stable and v6 is in development: https://github.com/PHP-DI/PHP-DI/blob/master/doc/migration/6.0.md
