### ISSUE TITLE
Compile `make()` calls

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#543]
`make()` is not using compiled code so it's not optimized. It could be great to have a look at what can be done here.

**Comment by amakhrov** [comment]
It's effectively a blocker for me. I make quite heavy use of `FactoryInterface::make` (instead of writing my own factory classes for each use case). Since caching has been removed in v6, there is no way to improve performance of those. So there is basically performance drop after v5 for my use case.

Having said that, I don't see an easy solution to the problem expect recursive traversal of the source files dir and adding definitions for all found class to the compiled container.

**Comment by mnapoli** [comment]
Thank you for the feedback, did you test v6 and see a slowdown? If so, by how much? This data could be useful.

> Having said that, I don't see an easy solution to the problem except recursive traversal of the source code dir and adding definitions for all found classes to the compiled container.

I'm not sure I understand, this would be useful to compile autowiring definitions, but it's not directly related to `make()`. If you are using autowiring, you can compile those definitions by adding an entry in the config for each class: `Foo::class => autowire()`

**Comment by amakhrov** [comment]
> did you test v6 and see a slowdown

Not yet. But I did test cached (APCu) vs uncached in v5 on my project and see how caching reduces run time of the dependency injection part of the app. I just assume that since dependencies build with `make()` calls are not compiled, a large part of the dependency tree will remain unoptimized.

> it's not directly related to `make()`.

It kind of is. Without using `make()`, I could just list all my entry points (controllers) in the php-di config as `autowire()`.
But because of `make()`, I now also need to list all classes that are instantiated using `make(MyClass::class)`.
`make()` calls happen in different parts / nesting levels of the app - making it harder to track. And it just increases the manually maintained php-di config a lot.

**Comment by mnapoli** [comment]
OK I understand. I think #547, combined with this issue, could help.

What difference in performance did you see?

**Comment by amakhrov** [comment]
#547 could be helpful, thanks.

I saw ~30ms difference with vs without cache.
Not huge - but quite an easy win.

**Comment by mnapoli** [comment]
#564 can be a solution to this ticket (adding a cache). Compiling make calls will be very hard (I'm not sure it's even possible in most cases), I think #564 might be a good alternative solution.

Please have a look and let me know what you think.

If these problems are out of the way v6 is done IMO.

**Comment by amakhrov** [comment]
@mnapoli that's great!
Restoring acpu caching as a last resort seems to be a wise solution.

**Comment by mnapoli** [comment]
@amakhrov would you have time to test #564 in the next days?

**Comment by holtkamp** [comment]
After finished migrating to `6.0.0-beta1` I notice a (significant) drop in performance, while having compilation enabled. We also use `make()` a lot so will try to use the suggested approach in https://github.com/PHP-DI/PHP-DI/pull/564

**Comment by amakhrov** [comment]
@mnapoli I'll run some tests today!

**Comment by mnapoli** [comment]
Thanks both!
