### ISSUE TITLE
Support PHP 7.1 and up

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#583]
Follow up of https://github.com/PHP-DI/PHP-DI/issues/483#issuecomment-372071094

We could switch to PHP 7.1 (http://php.net/supported-versions.php) but I don't see a lot to gain in the codebase. And keeping 7.0 allows more projects (especially open source ones) to switch to PHP-DI if they want to, an agressive requirement may hamper adoption.

Comments welcome!

**Comment by Taluu** [comment]
If it were up to me, we should consider 7.2 (`object` typehint among other things), especially as 7.1 will cease support in next December, and 7.0 has no support since last December.

**Comment by SvenRtbg** [comment]
There are not that many arguments to support that move from a technical side. Basically it boils down to typehints. The question would be if PHP-DI really benefits from having nullable typehints. Are there at least two instances in the code where a typehint had to be omitted because it could be `null` as well?

There are other effects that may be considered: Supporting less diverse PHP versions requires running less diverse test suites and allows using more modern features (as said type hints), so PHP-DI contributors and maintainers don't have to deal with legacy. I cannot evaluate if this is a huge benefit in itself.

Note that PHP 7.0 still gets security support until the end of this year, so technically it is still supported (and got it's latest CVE bugfix March 1st).

I'm biased. I'm switching from 5.5 to 7.0 right now (nothing more recent because the datacenter uses Suse SLES, with 7.0 being the latest supported version right now). However, I cannot come up with a good argument for such a situation that isn't blatantly selfish (like "support my version, please, it will make my life easier - I don't care about yours, though."):

- Looking at supported versions in distributions does not give you a clue about usage.
- Looking at Composer usage does not give you a clue about versions used in production.
- Looking at other peoples version all in all does not really help this project - if there is a very good use case only supported by PHP 7.2, the decisision should be made to switch to that version with a reasonable release version. New versions do not unrelease old versions, and supporting multiple versions isn't impossible, although undesirable for maintainers.

**Comment by mnapoli** [comment]
I was very eager to migrate to PHP 5.4, then 5.5, 5.6 and finally 7.0 because it was exciting and there were clear benefits.

Right now I don't mind much about 7.1 and 7.2 at the moment, it's really a detail (for PHP-DI). So I'd rather let as many people as possible use PHP-DI.

Maybe 7.3 will be really interesting and the situation will be different? I'm fine waiting a bit.

**Comment by mnapoli** [comment]
Outdated issue :)
