### ISSUE TITLE
php-di 6 change help 

### ISSUE THREAD

**Issue by spencer237** [PHP-DI/PHP-DI#587]
Hello everyone I just installed php-di 6 on my project and I realize that **constructorParameter** is no longer there, I would like to know if he has changed name if it is the case what if he Please.

**Comment by ldebrouwer-rmn** [comment]
@spencer237 It looks like you may have a type in the method name, the method is called `constructorParameter`.

**Comment by spencer237** [comment]
@ldebrouwer-rmn    In the method list of my php-di 6 there is only `constructor->` whereas I need `constructorParameter->`

**Comment by mnapoli** [comment]
Hi @spencer237, which helper are you using? `create()` or `autowire()` ?

With `create()` you have to use `->constructor` because you **need** to define all the parameters, so `->constructorParameter()` makes no sense.

With `autowire()` you have to use `->constructorParameter()` to customize what is injected in a specific parameter. All the other parameters are managed by the autowiring.

Does that make sense?

**Comment by spencer237** [comment]
@mnapoli Thanks
