### ISSUE TITLE
Getting cache misses after using apcu.

### ISSUE THREAD

**Issue by rquadling** [PHP-DI/PHP-DI#623]
Hi.

Just added a Doctrine/ApcuCache and things are going well. In our live environment, we're getting around 88% cache hits.

What I'm unsure is why, after the initial loading, we're getting any cache misses? The percentages seem to be stable 88.7% hits 11.3% misses

Is there a way we can debug (happy to break something in a test environment to see what's happening) what is being missed?

We are using default apcu installation (32Mb of mmap memory). The apc_status page is showing less than 1Mb used, so we don't think it is memory related.

![image](https://user-images.githubusercontent.com/12801/45046903-707e8b80-b06f-11e8-9515-b27a183fb21b.png)

We have 330-ish DI\Definition entries in the cache and nothing else. We use memcached for other things which need to be shared across multiple instances. We decided to not share the DI definitions in the same way as the overhead of reading them from another server seemed wasteful once a local apcu cache had them in memory.

**Comment by mnapoli** [comment]
I think this is because some definitions are not cached because they are not "cacheable".

https://github.com/PHP-DI/PHP-DI/blob/ef261dcf3f416f9365fb6c20c8cbf0daf06cc3f8/src/Definition/Source/SourceCache.php#L33-L42

As you can see we always fetch, but some definitions are never stored.

Why?

This is the default behavior on `Container::get()`:

- try to use compiled entries
- if miss then fallback to cache
- if miss then fallback to creating the definitions from config files

If some definitions are not compilable and not cacheable, there will be a miss.

Additionally there are other methods of `Container` that read definitions: `make()`, `call()` I think too, maybe others? This is why there is [this comment](https://github.com/PHP-DI/PHP-DI/blob/ef261dcf3f416f9365fb6c20c8cbf0daf06cc3f8/src/Definition/Source/SourceCache.php#L72) and [this comment](https://github.com/PHP-DI/PHP-DI/blob/ef261dcf3f416f9365fb6c20c8cbf0daf06cc3f8/src/Definition/Source/SourceCache.php#L74). Check out https://github.com/PHP-DI/PHP-DI/pull/564 to see more details as to why the cache was restored.

So maybe you have wildcard definitions, or other kind of definitions that are not compilable & cacheable?

Or maybe you are using `make()` (or another method) that bypasses the compiled entries, and as we can see the cache stores a very little subset of entries (only objects basically). If that's the case, maybe there are optimisations to do? I don't know for sure.

**Comment by rquadling** [comment]
Thank you for that. With the info you provided, I found several areas we can optimise to reduce the non-cacheable definitions.

**Comment by mnapoli** [comment]
Awesome, what did you do? Did you move some definitions from wildcards to explicit definitions?

**Comment by rquadling** [comment]
Our di-config file includes rules on making things that don't need to have explicit rules.
