### ISSUE TITLE
Parameter are not injected when it has a default values

### ISSUE THREAD

**Issue by javisr** [PHP-DI/PHP-DI#637]
Hi!

I'm not sure if this is an issue or not.

I have a definition like that 

```
return [
		\App\ViewInterface::class => \DI\create(\App\Views\Json::class),
		\App\Response::class => \DI\autowire()
];
```
then a class like

```
class Response {
    public function __construct(\App\ViewInterface $view = null){
        var_dump($view); die();
    }
}
```

What I was expecting was that the var_dump will show an \App\Views\Json object however it shows NULL.

If I remove the `= null` from the constructor it has the expected result but as I'm working on an app refactor I can't force the constructor to have a mandatory value.

Is this an issue or it is how it is supposed to work?

Thanks!

**Comment by javisr** [comment]
I guess I could change the definition to be like this,

```
return [
		\App\ViewInterface::class => \DI\create(\App\Views\Json::class),
		\App\Response::class => \DI\factory(function (ContainerInterface $c) {
			$view = $c->get(\App\ViewInterface::class);
			return new \App\Response($view);
		})
];
```

but I think that allowing the injection when the value is null could be a good feature. what do you think?

**Comment by mnapoli** [comment]
Hi, yes default values are used. Those have more priority than the type-hint when using autowiring.

The reason for that is that this is often used for "optional dependencies". And when those dependencies don't exist, we don't want to crash the application because we couldn't find the dependency, instead we want to use the default value.

We could change that to make it more intelligent:

- if the dependency exist, inject it
- else use the default value

but to be honest I think this may be complicated, and more importantly this would be quite magic.

There is already enough magic in PHP-DI ^^ I'd rather stick with a predictable behavior, even if it doesn't fit all use cases.

As you said, you can get around the issue by specifying the injection explicitly using the config.

**Comment by javisr** [comment]
Thanks for you anwser @mnapoli :)

**Comment by 6elkir** [comment]
Need review!
https://github.com/PHP-DI/PHP-DI/issues/911

**Comment by johnrobertcobbold** [comment]
Hello !

> default values are used. Those have more priority than the type-hint when using autowiring.

> We could change that to make it more intelligent:
> if the dependency exist, inject it
> else use the default value


Is this still the case in 2025 ? I assumed the behavior was indeed: inject the dependency if it exists, else use the default value 🙈 ...

I have a class like this for example with an optional logger:

`public function __construct(LibDb $libDb, ?LoggerInterface $logger = null)`

I assumed PHP-DI would auto-wire and inject the LoggerInterface but I keep getting null and was banging my head thinking it did not make sense.. Still considered to be too much magic @mnapoli  ? Thanks for the great library btw :)

**Comment by kristian-softtech** [comment]
> `public function __construct(LibDb $libDb, ?LoggerInterface $logger = null)`
> 
> I assumed PHP-DI would auto-wire and inject the LoggerInterface but I keep getting null and was banging my head thinking it did not make sense.. Still considered to be too much magic [@mnapoli](https://github.com/mnapoli) ? Thanks for the great library btw :)

This is the biggest issue I have with the PHP-DI handling of default parameters.

It's pretty common practice to have `LoggerInterface` parameters be defaulted with `LoggerInterface $logger = new NullLogger()` to simplify unit tests, but currently we can't use this because PHP-DI then just doesn't bother injecting the `LoggerInterface` service at runtime.

Perhaps a builder option `replaceDefaultParameters(bool $replace = true)` would satisfy both use cases? Could leave default behavior as-is for backward compatibility.
