### ISSUE TITLE
Website not available via https

### ISSUE THREAD

**Issue by thunderrabbit** [PHP-DI/PHP-DI#641]
As mentioned in https://doesmysiteneedhttps.com/ SSL certificates are free via https://letsencrypt.org/

**Comment by SvenRtbg** [comment]
I understand what you mean, but it looks like it's more complicated than you think it is. http://php-di.org/ offers a HTTPS variant https://php-di.org/ but the certificate used is broken because it is provided by GitHub, and isn't valid for that domain. 

The project uses Github pages (look at the "gh-pages" branch) to maintain and serve the documentation, and added some external domain hosting to get a catchy domain name for it. Fixing the HTTPS issue (which I agree is desirable - I've done it for my personal domain, which doesn't even host anything valueable) very likely will be a huge effort beyond "just click this button and enjoy HTTPS".

**Comment by thunderrabbit** [comment]
Fair enough; thanks for looking in to it.

**Comment by mnapoli** [comment]
Thanks @SvenRtbg for the details. Indeed what I've done in those cases is setup Cloudflare and proxy the domain to Cloudflare and use their SSL. This takes a little time to setup :/

**Comment by shadowhand** [comment]
Another option is to [migrate to netlify + jekyll][1], which I've done for all my open source projects that were previously on Github Pages. It is extremely easy and netlify is free for open source use.. [league/oauth2-client docs][2] contains an example.

[1]: https://www.netlify.com/blog/2017/05/11/migrating-your-jekyll-site-to-netlify/
[2]: https://github.com/thephpleague/oauth2-client/tree/master/docs

**Comment by webmaster777** [comment]
Github claims they have SSL-support for custom domain gh-pages using LE: https://github.blog/2018-05-01-github-pages-custom-domains-https/ 
You only need to migrate from A records to CNAME or ALIAS records in your dns. It seems you currently use A records, which explains why it wasn't automatically migrated.

Having the current situation with https://php-di.org/ showing a certificate warning is quite bad.

**Comment by mnapoli** [comment]
@webmaster777 I updated the A record to the new IP addresses (per the GitHub guide), yet the HTTPS version still shows an error.

Could you investigate and tell me what's missing?

**Comment by webmaster777** [comment]
I think it works now, though no css or images are loaded, probably due to wrong protocol?

**Comment by jdreesen** [comment]
Yes, all assets are included via HTTP, which gets blocked because of mixed content.

**Comment by webmaster777** [comment]
I don't know what happens if you change the `baseUrl` in `couscous.yml` to protocolless `//php-di.org` ?

**Comment by mnapoli** [comment]
Thanks! I guess GitHub needed time to accept HTTPS requests (the domain did propagate then). I fixed the mixed content issue.

https://php-di.org/ is now HTTPS-only.

Thanks all!
