### ISSUE TITLE
Autowiring for new Class instantiated inside a class?

### ISSUE THREAD

**Issue by alturic** [PHP-DI/PHP-DI#650]
I admit I'm extremely fresh when it comes to reflection and PHP-DI, however I don't think I've come across this in Symfony or Laravel, not to compare, just using it as an example of my autowiring experience.

I have a controller that is called, and all dependencies in it's __construct are autowired correctly. Inside of this class, I have a method that `return new FooClass();`, and I'm wondering if autowiring is supposed to work from the FooClass __constructor? It's calling 2 dependencies, both of which are also used in the class that's instantiating FooClass (not that I'm expecting it to pass those in), but should PHP-DI be autowiring the dependencies when FooClass() is instantiated like it does for the controller? If not, am I doing something quirky that I really shouldn't be doing?

**Comment by mnapoli** [comment]
Hi, I invite you to read this guide http://php-di.org/doc/getting-started.html as well as http://php-di.org/doc/understanding-di.html

And to quickly answer your question PHP-DI will not inject dependencies in `new FooClass()`.

**Comment by SvenRtbg** [comment]
In addition: Not every case of creating an object needs DI - it depends on how much flexibility really is required by the problem you want to solve.

For example, the objects created by querying a database or when processing a HTTP request's query string or POST data are usually not created with dependency injection. The table structure or the HTTP data format is fixed, so the object representing it most likely has properties or getters for all of them. And it's lifetime is shorter that that of the application itself. Injecting these objects will not help you 99% of the time.

If you need the flexibility to create "any" object and determine this outside of a class, you'd probably either inject a prototype of if that gets cloned before being returned (so you clone the object being given, then put the data in, then return it), or you inject an instance of a factory that creates the object for you. In both cases you'd have to address the problem of "What kind of object do I really get, and which properties and methods does it have?", so you still have to care about the objects somehow, e.g. have them (there must be more than one, otherwise simply `new MyObject`) implement an interface that allows common access to fill and retrieve data.

**Comment by alturic** [comment]
Well, it was really a question of _when_/_how_ it knows to autowire, vs `return new FooClass();` wouldn't auto-wire.
