### ISSUE TITLE
Bug or misunderstanding of wrapContainer functionality?

### ISSUE THREAD

**Issue by mbaumgartl** [PHP-DI/PHP-DI#670]
I'm trying to implement a parent/child relationship with `ContainerBuilder::wrapContainer`. In my project I want to define common dependencies/services in a parent container and pass it around to submodules with own containers.

Here is a simplified example:
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

class Test {
    private $url;
    public function __construct(string $url) {
        $this->url = $url;
    }
}

$builder = new \DI\ContainerBuilder();
$builder->addDefinitions([Test::class => \DI\autowire()->constructor('https://example.com')]);
$root = $builder->build();

$builder = new \DI\ContainerBuilder();
$builder->wrapContainer($root);
$child = $builder->build();

echo 'child container knows definition: ', print_r($child->has(Test::class), true), \PHP_EOL;
$child->get(Test::class);
```
When the snippet is executed it results in:
`Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition: Entry "Test" cannot be resolved: Parameter $url of __construct() has no value defined or guessable`

I'm using the most recent version (`composer info | sort`):
```
jeremeamia/superclosure 2.4.0   
nikic/php-parser        v4.2.2  
php-di/invoker          2.0.0   
php-di/php-di           6.0.8   
php-di/phpdoc-reader    2.1.0   
psr/container           1.0.0   
symfony/polyfill-php56  v1.11.0 
symfony/polyfill-util   v1.11.0 
```

Is it a bug or do I have to use `\Acclimate\Container\CompositeContainer` instead?

**Comment by holtkamp** [comment]
And the `$root` Container "does" work?

```php
$root->get(Test::class);
```

**Comment by mbaumgartl** [comment]
Yes, it's working as expected! :smiley: 

```php
var_dump($root->get(Test::class));
```
outputs:
```
object(Test)#26 (1) {
  ["url":"Test":private]=>
  string(19) "https://example.com"
}
```

**Comment by SvenRtbg** [comment]
It's a misunderstanding of the wrap feature.

First of all, this wrapping feature was not continued in the PSR ContainerInterface, it is only mentioned and defined in the previous standard attempt https://github.com/container-interop/container-interop/blob/master/docs/ContainerInterface.md

If you read that part, you'll quickly discover that your child, which is wrapping something, does not directly know about `Test`, so it has to return `false`. However, if the child container knows any other class, for ALL dependencies of that definition, it has to look into the wrapped root container.

I'll assume this is done in order to prevent recursion loops, and you can easily work around this by using additional container implementations. But also note: If you stick your child and root container into a `CompositeContainer` without the child wrapping the root, it would still not work, because the child has to lookup dependencies from root, and from itself. This will only work if you wrap the `CompositeContainer` inside of the child container, and add the child and root to it.

**Comment by holtkamp** [comment]
>But also note: If you stick your child and root container into a CompositeContainer without the child wrapping the root, it would still not work, because the child has to lookup dependencies from root, and from itself. This will only work if you wrap the CompositeContainer inside of the child container, and add the child and root to it.

I also encountered this recently: when using multiple containers and not configuring this properly, multiple instances of the same resources can occur. 

It became a bit too complex so I decided to extend the `DI\Container` with my own class `XYZContainer` and instructed the PHP-DI ContainerBuilder to use that class name. But the approach with a composite container and wrapping seems to be more elegant. 

So this should work to have two containers which act as primary and secondary (fallback) container?:

```php
$compositeContainer = new \UltraLite\CompositeContainer()

$builder = new \DI\ContainerBuilder();
$primaryContainer = $builder->build();

$builder = new \DI\ContainerBuilder();
$builder->wrapContainer($compositeContainer);
$builder->addDefinitions([Test::class => \DI\autowire()->constructor('https://example.com')]);
$secondaryContainer = $builder->build();

$compositeContainer->addContainer($primaryContainer); //First look in primary container
$compositeContainer->addContainer($secondaryContainer); //Use the child case a resource does not exist
```

@mbaumgartl sorry for hijacking your issue 😄 , but maybe we are looking for the same thing. I am experimenting with a ["HandWritten" Container](https://matthiasnoback.nl/2019/03/hand-written-service-containers/) to act as primary container, while using the regular PHP-DI container as secondary / fallback container.

**Comment by mbaumgartl** [comment]
@SvenRtbg Thanks for pointing to the PSR document and your detailed explanation of composing containers.

**Comment by mbaumgartl** [comment]
@holtkamp No problem :wink: 

The article about handwritten containers is interesting. I see the advantages, but I'm unsure if this approach scales with project size.
