### ISSUE TITLE
Resolve splat operator from parent class

### ISSUE THREAD

**Issue by hugochinchilla** [PHP-DI/PHP-DI#678]
Since PHP introduced the splat operator I find myself writing a lot of code like this:

```php
<?php

class BaseClass
{
    private $foo;

    public function __construct(Foo $foo)
    {
        $this->foo = $foo;
    }
}

class Example extends BaseClass
{
    private $bar;

    public function __construct(Bar $bar, ...$args)
    {
        $this->bar = $bar;
        parent::__construct(...$args);
    }
}
```

Sadly if I try to use DI to build an instance of `Example` I get an error like this one:

```
DI\Definition\Exception\InvalidDefinition: Entry "Example" cannot be resolved: The parameter "args" of __construct() has no type defined or guessable. It has a default value, but the default value can't be read through Reflection because it is a PHP internal class.
Full definition:
Object (
    class = Example
    lazy = false
    __construct(
        $bar = get(Bar)
        $args = #UNDEFINED#
    )
)
```

Would it be possible to support this kind of writing by looking at the parent class or providing any kind of hinting in the DI config?

**Comment by SvenRtbg** [comment]
Your inner passing of arguments looks quite wrong, probably Foo should go into the parent constructor. But I get your point.

Have you tried defining a constructor parameter for Example? Like autowire()->constructorParameter("args", [])

**Comment by mnapoli** [comment]
> Would it be possible to support this kind of writing by looking at the parent class

I see. Your usage of the splat operator + parent constructor is quite specific, and it is a convention. Nothing we would want to include inside PHP-DI itself (because it is your specific convention).

> or providing any kind of hinting in the DI config?

As @SvenRtbg pointed out you can hint (manually) the container what to inject. But except that I'm not sure if there are alternatives.

**Comment by hugochinchilla** [comment]
@SvenRtbg there was an error in the code, is now fixed.

Hinting args to an empty array is only a solution to move the error from php-di to the constructor of my class, not a real solution.

@mnapoli could be this handled by a custom resolver as requested in #553?

Anyway, in python it's quite common practice to use `*args` and `**kwargs` for this same purpose, I would expect this convention to become a standard convention over time.

**Comment by mnapoli** [comment]
I'm not sure it could as there are _a lot_ of consequences on PHP-DI's internals.

If you have a convention like this, a solution could be to create your custom helper to save yourself from writing repetitive code. For example you could create a function to avoid typing `autowire()->constructorParameter("args", [])` every time.

**Comment by hugochinchilla** [comment]
@mnapoli but injecting an empty array to `$args` is not a solution.

I need args to resolve to `[new Foo()]`, and Foo could have it's own dependecies as well, in fact it has to resolve to `[get(Foo::class)]`

**Comment by avant1** [comment]
As a PHP developer who uses Python a lot I would like to add a side note:
> Anyway, in python it's quite common practice to use *args and **kwargs for this same purpose, I would expect this convention to become a standard convention over time.

This convention sometimes may be useful, but it often leads to hidden errors and makes using such code much more complicated. 

As `Example` class user I should know dependencies of its base class. Otherwise how can I create `Example` instance? I have to go to source code, find its parent class, review constructor parameters. This introduces hidden dependency between classes and requires deep internal knowledge about implementation details. 
All I want is to create `Example` instance, how would I know that I should pass `Foo` instance as a second parameter?
Adding new required parameters to `BaseClass` constructor does not tell anybody that `Example` constructor parameters should be updated too. I'm not sure if any static analysis tool for PHP can notice such kind of error.

Using Python libraries that define function arguments as `**kwargs` is a pain for me. I should stop writing code and start reading documentation. There is no autocompletion and invalid keyword parameter names detection in IDE.

So I hope this would not become a convention in PHP.

**Comment by mnapoli** [comment]
> @mnapoli but injecting an empty array to $args is not a solution.

Right my bad sorry.

So it comes down to: you need to configure what to inject (via the usual means that PHP-DI exposes to you). PHP-DI will not implement that specific convention at the moment as it is not a convention in PHP applications.

Feel free to continue the discussion, I'm closing to keep the issue tracker clean.

**Comment by hugochinchilla** [comment]
It's fine, and @avant1 has a point here, I will just make the dependencies explicit.
