### ISSUE TITLE
[question] Decorate all resolved instances from a certain type

### ISSUE THREAD

**Issue by hugochinchilla** [PHP-DI/PHP-DI#689]
Hello, I've a question which may seem a little odd, so I will explain the context in which I need it so you can advise me better alternatives if possible.

My application services are using a base class similar to this one:

```php
abstract class Service
{
  public function call(...$args)
  {
    $this->logCall($this, $args);
    try {
      return $this->execute(...$args);
    } catch (\Exception $e) {
      $this->logException($this, $e);
      throw $e;
    }
  }
  
  abstract protected function execute(...$args);
}

class ConcreteService extends Service
{
  protected execute(Foo $foo)
  {
    // do something
  }
}

$service = $container->get(ConcreteService::class);
$service->call($foo) // gets free logging
```

Any service created in the application extends from this class and implements the `execute()` method, by using this base class we get free logging of the inputs of every service and very good trace-ability.

The problem with this is that we don't get good IDE auto-completion for the `call()` signature of a given service.

I would like to get rid of this implementation and remove this `call()` so i end up with something like this:

```php
abstract class Service
{
    abstract public function call(...$args);
}

class ExampleService extends Service
{
  public function call(Foo $foo)
  {
    // do something
  }
}
```

### So the problem is:

I would like to intercept the resolutions made by the container in way that I can wrap subclasses of `Service` in a decorator which handles logging automatically, any advice in how to accomplish this?

**Comment by SvenRtbg** [comment]
You can already override `call()`, call  `parent::call($arg)` inside, get the generic logging and still have individual method signatures.

However, your real problem is that all services inherit from the same type. If you want to put the same code in many classes (for logging or something else) without inheriting, that's what "traits" are for: PHP-engine powered copy&paste of code. The trait would provide the `logCall()` and `logException()` code without inheritance, the `call()` gets an individual signature per service, and still has to call the logging methods. That part cannot be avoided to copy, but you could get rid of the internal `execute()`.

**Comment by hugochinchilla** [comment]
@SvenRtbg you are right about having all the services inheriting from the same type is not a good thing and yes I could use a trait to make this methods available, usually many of this services get a logger injected anyway so it may not be necessary for many of them.

The thing is, this is a legacy app with many years of development, we are doing small steps to make it better, and the change I wan't to make makes a huge improvement in development experience because of the IDE being able to provide precise information about the types you need to pass to a service instance. The problem is that by doing so we loose the trace-ability we already have. What I look here is for a quick win (if it exists) that may enable us to apply this change to our base class and not loose the automated input/output logging.

**Comment by hugochinchilla** [comment]
Also, I've edited the first example to better represent our use-case.

**Comment by SvenRtbg** [comment]
Have you considered this combination of your two examples as a temporary solution:

    class ConcreteService extends Service
    {
      // add this method to make the IDE happy
      public function call(Foo $foo)
      {
        return parent::call($foo);
      }

      protected execute(Foo $foo)
      {
        // do something
      }
    }

PHP-DI allows some kind of decoration, see http://php-di.org/doc/php-definitions.html#decoration - however this does not look like you could use it as a solution. Compare this to the concept of [initializers in Zend Servicemanager](https://docs.zendframework.com/zend-servicemanager/configuring-the-service-manager/#initializers), where you are able to interact with every object that gets created and do anything with them before passing it to the application. PHP-DI does not have such thing, most likely because this is highly inefficient - each initializer is called for every object and then has to decide if it will act or not.

The other downside of Zend Servicemanager is it's excessive configuration itself - that's why I use PHP-DI's autowiring for some time now.

**Comment by hugochinchilla** [comment]
@SvenRtbg that would work but it has the same problem as your first proposal (which I forgot to point out), that would mean editing more than a thousand services, I need something that can patch my code in runtime.

**Comment by SvenRtbg** [comment]
PHP-DI cannot help you patching the source code, unfortunately. Because that's what you'd have to do in order to benefit from it in the IDE.

But I think my suggestion allows you to patch one service at a time without interrupting operations, and instantly getting the benefit for every changed service. Yes, still you have to edit all the services, but it has not to happen all at once.

**Comment by mnapoli** [comment]
As it has been explained, PHP-DI does not offer such feature. The main reason is that this is a pattern that I think should be avoided. But I definitely understand your situation:

> The thing is, this is a legacy app with many years of development, we are doing small steps to make it better

What you could do is create a function like `DI\autowire()` or `DI\create()`: that function could auto-register your decorator?
Or another solution would be to heavily override PHP-DI, but that will probably be a nightmare to maintain.

**Comment by holtkamp** [comment]
@hugochinchilla 

>that would mean editing more than a thousand services

Maybe you can have a look at https://github.com/rectorphp/rector by @TomasVotruba which specializes in this kind of massive refactors. Might take some time to prepare, but might be worth it?

**Comment by hugochinchilla** [comment]
thanks for all of your suggestions!
