### ISSUE TITLE
One interface to multiple classes

### ISSUE THREAD

**Issue by davidgithub1980** [PHP-DI/PHP-DI#702]
Hi. I believe there is one use-case missing in the docs that I am not sure how to resolve.

Suppose I have **Logger1** and **Logger2** entities. Both of them implement **LoggerInterface**. I would like to inject both of them by interface, i.e. inject _Logger1_ into **Controller1** via an interface and inject _Logger2_ into **Controller2** via an interface.

Is this possible via the array-like definitions file? The _LoggerInterface_ in the docs deals with one Logger entity only.

**Comment by elie29** [comment]
IMHO, you need to use constants in order to define with concrete class you need to use in your class. Because at the end you need one class to be injected not both of them.

However, if you intent to use both of them, try to use [decorators](http://php-di.org/doc/definition-overriding.html#decorators)

Regards.

**Comment by juliangut** [comment]
@davidgithub1980 that is a pretty normal use-case which cannot be resolved by itself using only one interface (LoggerInterface in your example)

Depending on your specific case you'd use one of the following strategies:
1. If you only need one of the loggers in a single place I'd prepare a definition [factory](http://php-di.org/doc/php-definitions.html#factories) in which you instantiate the specific implementation. Quick and clean
2. If you really make use of both implementations throughout the system I'd create an empty-dummy interface and make one of the loggers implement it

Hope it helps

**Comment by mnapoli** [comment]
👍  @juliangut 

I would also recommend writing configuration. Yes it is verbose, but that is also explicit.

**Comment by SvenRtbg** [comment]
I'd love to give an alternative answer, but there is none.

If you autowire, the interface has to resolve to exactly one class or factory call, and the factory only knows to create an instance, it does not know where it will be put. 

So the second approach is to explicitly configure all your controllers to explicitly include the logger they need, or maybe only the ones that deviate from the default logger case.

In my case, I'd like to have a different parameter for each logger instance depending on where it get's injected, but as the factory does not know which location the instance will end up, it cannot put that information into the creation process. But it isn't the end of the world, it only makes identifying the log results a little bit harder because they cannot state which class created them.

Other DI frameworks do have means to make this work, for example the Laminas (Ex-Zend) servicemanager has a mechanism of "initializers", i.e. your class implements some sort of trigger interface like `LoggerAware` that forces a method `setLogger()` to be present, and the initializer then gets the instance of the class and can inject a logger via setter injection. By doing this, it can inspect the instance because it is already created, and detect the classname before injecting. 

The drawback is that every instance that is ever created has to pass through every initializer that exists, and has to be checked if it supports the things a particular initializer is looking for. The other drawback is that you do setter injection, i.e. you cannot be sure that that setter has been called and you have to account for ending up without a logger in your code somehow. 

These two drawbacks are more serious to me than the issue with the logging, but YMMV. There are alternative DI frameworks out there that may support your use case better, but they usually do not support autowiring - which is the best feature in PHP-DI!
