### ISSUE TITLE
Call without override Parameters

### ISSUE THREAD

**Issue by ASmallCookie** [PHP-DI/PHP-DI#715]
Hello, 

I have the method of a class which needs other dependencies and an optional parameter :
```php
public function handleRequest(AltoRouter $router, FactoryInterface $factory, ?string $url = null): bool
{
 //... 
}
```

The problem is when I use call to call my method, using the parameter array **will overwrite all the parameters**.
```php
$container->call([\App\Kernel::class, 'handleRequest'], ['/']);
// TypeError : Argument 1 passed to App\Kernel::handleRequest() must be an instance of AltoRouter, string given
// This isn't an instance of AltoRouter anymore cause PHP-DI override them. 
```

Is it possible that PHP-DI injects all the necessary dependencies and lets me inject the chosen parameters without overwriting them?

Thank you very much for the support ❤.

**Comment by SvenRtbg** [comment]
When I look at the documentation for `call()`, I see the first example covering exactly your case, doesn't it? Named parameters: http://php-di.org/doc/container.html#call

**Comment by ASmallCookie** [comment]
I've only been using PHP-DI for a few days now, so I'm still struggling with it.

I did look at the documentation but how can this apply to me? Am I missing something? 

**I guess I have to do something like this? In order to redefine the parameters :**
```php
$container->call([\App\Kernel::class, 'handleRequest'],
            [
                $container->get(AltoRouter::class),
                $container->get(\DI\FactoryInterface::class),
                '/'
            ]);
```

**Comment by SvenRtbg** [comment]
In your second post, you are using an array that provides values for all parameters, and the order of the parameters in the array is identical to the order in the function definition. This is completely fine, and you can go with that.

I was suggesting that contrary to the way PHP usually works, you can do this:

    $container->call([\App\Kernel::class, 'handleRequest'],
            [
                'url' => '/'
            ]);

Note that the name of the variable `$url` is appearing inside the parameter array as a string. As I said, this is unusual for PHP, which does not have a built-in way of passing parameters to functions other than in the defined order. PHP-DI supports it because it's most loved feature, autowiring, plays nicely together with this: If you need a parameter to be populated, you are not forced to manually add any parameter values - they would still be figured out automatically. And I think that's what you are trying to do here, too.

**Comment by ASmallCookie** [comment]
**That's exactly what I wanted.**
All right, thank you very much for the explanation.

Appreciate it.
