### ISSUE TITLE
ReflectionParameter::getClass is deprecated in PHP 8

### ISSUE THREAD

**Issue by timfennis** [PHP-DI/PHP-DI#727]
I'm testing out PHP-DI on PHP 8 and noticed that it's throwing some deprecation warnings. If this issue is not wanted feel free to delete it.

```
Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/vendor/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php on line 65
```

and

```
Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php on line 45
```

**Comment by timfennis** [comment]
In ReflectionBaseduaowiring.php chaning getparamtersDefinition to something like

```
    private function getParametersDefinition(\ReflectionFunctionAbstract $constructor) : array
    {
        $parameters = [];

        foreach ($constructor->getParameters() as $index => $parameter) {
            // Skip optional parameters
            if ($parameter->isOptional()) {
                continue;
            }

            $type = $parameter->getType();
            $class = null !== $type && !$type->isBuiltin() ? $type->getName() : null;

            if ($class) {
                $parameters[$index] = new Reference($class);
            }
        }

        return $parameters;
    }
```

seems to work. (Solution based on pull-requests seen elsewhere).

For FactoryParamterResolver.php the following solution appears to work:

```
    public function getParameters(
        ReflectionFunctionAbstract $reflection,
        array $providedParameters,
        array $resolvedParameters
    ) : array {
        $parameters = $reflection->getParameters();

        // Skip parameters already resolved
        if (! empty($resolvedParameters)) {
            $parameters = array_diff_key($parameters, $resolvedParameters);
        }

        foreach ($parameters as $index => $parameter) {
            $type = $parameter->getType();
            $class = null !== $type && !$type->isBuiltin() ? $type->getName() : null;

            if (!$class) {
                continue;
            }

            if ($class === 'Psr\Container\ContainerInterface') {
                $resolvedParameters[$index] = $this->container;
            } elseif ($class === 'DI\Factory\RequestedEntry') {
                // By convention the second parameter is the definition
                $resolvedParameters[$index] = $providedParameters[1];
            } elseif ($this->container->has($class)) {
                $resolvedParameters[$index] = $this->container->get($parameterClass->name);
            }
        }

        return $resolvedParameters;
    }
```

I'm not very familiar with php-di and I can't tell if these are actual solutions which is why I've neglected to make a pull-request.

**Comment by mnapoli** [comment]
In this pull request I fixed a few things for PHP 8 support: https://github.com/PHP-DI/PHP-DI/pull/726/commits

I think we'll have to support PHP 8 in PHP-DI 6 anyway, so it might be worth applying these "PHP 8" commits on master too.

**Comment by Findus23** [comment]
@mnapoli Just to be clear: Would it be possible to include the PHP 8 support (9218e5461fb1eed1c64eb6306febea9c8175ce48) also in PHP-DI 6 (which support PHP 7.2+)? That would be really great for Matomo.

**Comment by mnapoli** [comment]
@Findus23 yes, PHP-DI 6 should support PHP 8.

**Comment by Findus23** [comment]
@mnapoli As the last PHP8 beta was released, it would be amazing if you could publish a new PHP-DI 6 version including the PHP 8 compatibility.

**Comment by mnapoli** [comment]
After spending a good amount of time into this, PHP 8 support for PHP-DI 6 is harder than I anticipated because of https://github.com/PHP-DI/PhpDocReader/issues/19.

Since there is already more work on PHP-DI to do, my current plan is to support PHP 8 in PHP-DI 7 (which drops the need for PhpDocReader, i.e. it removes the problem).

If anyone wants PHP 8 support for PHP-DI 6, please work on PhpDocReader to support PHP 8. If you can't, you can also hire me to work on that (with enough time I know I can), but at the moment I cannot spend a whole day working on this on my own time.

**Comment by tsteur** [comment]
Hi @mnapoli we at Matomo would sponsor it. I get Matt to reach out to you. We'd require PHP 7.2.5+ support though and not PHP 7.3+. Currently we're using PHP DI 6.2.1 in Matomo AFAIK https://github.com/matomo-org/matomo/blob/4.x-dev/composer.lock#L1219

**Comment by mnapoli** [comment]
@tsteur thanks, email received!

**Comment by mnapoli** [comment]
[PHP-DI 6.3 is released with PHP 8 support 🎉 ](https://github.com/PHP-DI/PHP-DI/releases/tag/6.3.0).

Thanks a lot to the [InnoCraft](https://www.innocraft.com/) team, the makers of [Matomo](https://matomo.org/), for sponsoring this release!

Let me know of any compatibility you may see, all dependencies have been upgraded and tested as well. For those curious, all tests are now running on GitHub Actions because Travis CI does not support PHP 8 yet.
