### ISSUE TITLE
caching vs autowire

### ISSUE THREAD

**Issue by zabakala** [PHP-DI/PHP-DI#731]
Hi, I would a clarification on the following issue. On the one hand the docs say, when it comes to using _autowire_ inside a definition file:

`// when using no option it is not necessary to write it in the config file`

...but on the other hand the docs also say, when it comes to caching:

```
Compiling the container is the most efficient solution, but it has some limits. The following cases are not optimized:
- autowired (or annotated) classes that are not declared in the configuration
```

Is it possible to provide a deeper insight into whether or not the absence of _autowire_ has a negative performance impact?

**Comment by mnapoli** [comment]
Right, indeed if you put it in the config file, then it _could_ be faster because it will be in the compiled container.

If you don't, the reflection will be read at runtime.

Now the question is: is reading the reflection a bottleneck in your application? It very well could be, but I'm just trying to provide some perspective :) (I don't want people to think that they _must_ or even _should_ optimize for this, in almost all of my applications I don't).
