### ISSUE TITLE
Method SoapClient::__construct() does not exist

### ISSUE THREAD

**Issue by eebanos** [PHP-DI/PHP-DI#733]
Hi everyone,
I'm having issues trying to instantiate the SoapClient class from the 'services' definition as follows:
services.php
```
return function (ContainerBuilder $containerBuilder) {
$containerBuilder->addDefinitions([
/**
* others definitions are included before, like 'LoggerInterface::class'....
*/
        SoapService::class => DI\create(SoapService::class)->constructor(
            get(LoggerInterface::class),
            DI\create(SoapClient::class)->constructor(get('wsxml.full')),
        )
]);
};
```
The parameter 'wsxml.full' is defined on config.php with the full WSDL Url and it is being resolved without problems.
When I do a request to the endpoint that requires the SoapService, it returns the following error response:
```
{
  "error": {
    "type": "SERVER_ERROR",
    "description": "Method SoapClient::__construct() does not exist"
  }
}
```

The only way I get it to work is creating the instance with 'new':
```
return function (ContainerBuilder $containerBuilder) {
$containerBuilder->addDefinitions([
/**
* others definitions are included before, like 'LoggerInterface::class'....
*/
        SoapService::class => DI\create(SoapService::class)->constructor(
            get(LoggerInterface::class),
            new SoapClient('fullUrlParameter')
        )
]);
};
```
But this way I can't pass the resolved parameter inside the constructor.

I'm using the Slim framework v4, PHP v7.4.9 with the ext-soap enabled.
Any ideas why it is not working as expected?

**Comment by SvenRtbg** [comment]
I'd think that the SoapClient is some sort of a non-standard class, because it is provided directly by an extension.

So in essence: `SoapClient::__construct()` is only an alias to `SoapClient::SoapClient()`, which is (if you remember these times) the outdated PHP4-style constructor method. If you analyse the class with Reflection, you will not detect the alias method, but only the oldstyle constructor (I tested with the oldest PHP 7.0.30 available to me - unfortunately 3v4l.org does not provide the soap extension, so no cross version examination).

Solution: You have to create a factory for your SoapClient, or for the whole `SoapService` object. If you use `\DI\create()`, then `__construct()` will be analysed for parameters, which does not work here.

Factories: https://php-di.org/doc/php-definitions.html#factories

**Comment by eebanos** [comment]
Thank you!!!, I ended using a factory as recommended:
```
        'SigoSoapClient' => DI\factory(static function (\Psr\Container\ContainerInterface $container) {
            return new SoapClient($container->get('wsxml.baseUrl') . $container->get('wsxml.wsdl'));
        }),
```
