### ISSUE TITLE
Removing a dependency

### ISSUE THREAD

**Issue by williamdes** [PHP-DI/PHP-DI#743]
Hi! 
This lib seems great! 
I will have a try to replace symphony's on phpMyAdmin. 

Would it be possible that the phpdoc reader is removed from the vendor folder but the lib would still work fine? 

I am asking that because we have users that delete files they consider useless to have a minimal phpMyAdmin. Security considerations,... 
See: https://github.com/phpmyadmin/phpmyadmin/issues/16418
I inspected all your dependencies and they are very clean. A very small tree 👏 

https://github.com/PHP-DI/PHP-DI/blob/955cacea6b0beaba07e8c11b8367f5b3d5abe89f/src/Definition/Source/AnnotationBasedAutowiring.php#L18

If your lib is approved I will need to package it into Debian https://packages.debian.org/search?suite=buster&section=all&arch=any&searchon=names&keywords=php+di
And each of it's dependencies too.

**Comment by mnapoli** [comment]
Hi! That would be great news if phpMyAdmin were to use PHP-DI!

And that's well spotted, indeed PhpDocReader is only needed when using annotations (just like the Doctrine annotations package): it could be an optional package like Doctrine.

The problem I see would be the BC break: users would update PHP-DI and their project may break without notice. I'm not sure how to solve this. PHP-DI 7 (#726) could be a solution as it drops more dependencies, however it requires PHP 7.4, which may be a deal breaker for you?

**Comment by williamdes** [comment]
Hi!
Thank you for quick response!
Well php 7.4 is too much for us for now, 7.1 is the actual minimum I think.

But I would be very happy if your test suite is checking if the library exists and  then run the test. 

This will help me a lot if I package your library on Debian.
Chicken and egg issue, I need to package your dependencies before the main library, etc.. 
This is hypothetical but can add months to an approval process on the Debian side.

Basically I would say: be sure your library runs fine without this dependency :)

Also I was asking myself is php-di compatible with this yaml like config files for symphony?
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/services.php
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/services_controllers.php

Here is the loader: https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/services_loader.php

I ditched out the yaml lib because it was a parsing  pile of costly php string functions calls on each request. (https://github.com/phpmyadmin/phpmyadmin/pull/16007)

**Comment by mnapoli** [comment]
> But I would be very happy if your test suite is checking if the library exists and then run the test.

That sounds doable, but I'm a bit confused: do you need to run PHP-DI's tests? If you do, then you have to install much more dependencies (`require-dev`), so that will be much harder I guess? I will assume in the rest of my comment that you don't need tests at all.

> Basically I would say: be sure your library runs fine without this dependency :)

We could indeed do something like this:

https://github.com/PHP-DI/PHP-DI/blob/f16f27b7bc0876c7e76f568e0733d59997c8ec9c/src/Proxy/ProxyFactory.php#L84-L86

and keep `composer.json` without change. That way there is no impact for Composer users. On your side, if you are able to package PHP-DI without phpdocreader, then all is good. As long as you don't use annotations (which AFAICT you don't with Symfony) you will not have any issue.

> Also I was asking myself is php-di compatible with this yaml like config files for symphony?
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/services.php
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/services_controllers.php

No, each DI container has its own configuration format. I'd be happy to help with the migration if you need.

Here is a preview of `services.php`:

**Before:**

```php
return [
    'services' => [
        'advisor' => [
            'class' => PhpMyAdmin\Advisor::class,
            'arguments' => [
                '$dbi' => '@dbi',
                '$expression' => '@expression_language',
            ],
        ],
        'browse_foreigners' => [
            'class' => PhpMyAdmin\BrowseForeigners::class,
            'arguments' => ['@template'],
        ],
        'config' => [
            'class' => PhpMyAdmin\Config::class,
            'arguments' => [CONFIG_FILE],
        ],
```

**After:**

```php
use funtion DI\create;
use funtion DI\get;

return [
    'advisor' => create(PhpMyAdmin\Advisor::class)
        ->constructor(get('dbi'), get('expression_language')),
    'browse_foreigners' => create(PhpMyAdmin\BrowseForeigners::class)
        ->constructor(get('template')),
    'config' => create(PhpMyAdmin\Config::class)
        ->constructor(CONFIG_FILE),
```

Note that using anonymous functions is also possible if you prefer:

```php
return [
    'advisor' => function (ContainerInterface $c) {
        return new PhpMyAdmin\Advisor($c->get('dbi'), $c->get('expression_language'));
    },
    // ...
```

You could also use autowiring (without annotations) if you wanted to simplify your config further: https://php-di.org/doc/autowiring.html

One difference to mention with the Symfony container is that PHP-DI does not differentiate parameters and services: `set()` and `get()` are for both (everything is mixed in one array).

`$containerBuilder->setAlias('dbi', DatabaseInterface::class);` can be replaced by `$containerBuilder->set('dbi', DI\get(DatabaseInterface::class));` (`get()` is a way to reference another entry without actually "getting" it from the container immediately).

**Comment by williamdes** [comment]
Hi from :fr: !

> That sounds doable, but I'm a bit confused: do you need to run PHP-DI's tests? If you do, then you have to install much more dependencies (require-dev), so that will be much harder I guess? I will assume in the rest of my comment that you don't need tests at all.

Well, I did skip some explanations here.

#### Debian packaging from what I do and understand

Each package must have it's dependencies packaged one by one.
No uploading the vendor folder and go. That will just be refused.
For obvious reasons: security patches, etc...

Another example: https://salsa.debian.org/php-team/pear/php-dasprid-enum
Case study (my package): https://salsa.debian.org/phpmyadmin-team/mariadb-mysql-kbs

What I did: opened a [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947975), imported the upstream tarball (from github links). See the file [here](https://salsa.debian.org/phpmyadmin-team/mariadb-mysql-kbs/-/blob/main/debian/watch#L4).
The import step is important because it relies on `git archive` that GitHub gives us.

This line will be a problem for me if I package: https://github.com/PHP-DI/PHP-DI/blob/7ab5ac6d7fc8f03ee943e386e5be666f0bd3b407/.gitattributes#L3

Then I do some config, fill out copyrights, etc...
See the example commit: https://salsa.debian.org/phpmyadmin-team/mariadb-mysql-kbs/-/commit/aa66b1e4700d0eb1c3cd843dede91744108912a7

Debian has a system to [auto test packages](https://salsa.debian.org/phpmyadmin-team/mariadb-mysql-kbs/-/jobs/1060116) named [autopkgtest](https://wiki.debian.org/ContinuousIntegration/autopkgtest): basically it is here that we need your test suite to work.

> do you need to run PHP-DI's tests?

Now you normally understand what I wanted to have without explaining it ;)


> We could indeed do something like this

Exactly, this is what I did on [mariadb-mysql-kbs](https://github.com/williamdes/mariadb-mysql-kbs/blob/deaa8204e46a2af4947489d348a58331367d5d94/test/DataTest.php#L36) to avoid packaging the json schema testing dependency I have.

> then you have to install much more dependencies (require-dev), so that will be much harder I guess?

Here is why if you remove "useless" dependencies and keep phpunit the testsuite "must" run and not throw errors.
One more dep, and it is one more package to maintain and that can cost a lot of time.

#### Implementation

> No, each DI container has its own configuration format. I'd be happy to help with the migration if you need.

I would prefer having a compatibility because all this function calls make the file less readable.

> Note that using anonymous functions is also possible if you prefer

They seems much more clean and clear.

A foreach would not be possible to make things compatible ?


I am not sure to implement your lib but it would be cool to implement it at phpMyAdmin.
I was thinking that DI libs where more exchangeable than what I see :thinking: ?

**Comment by mnapoli** [comment]
I'm sorry, I still don't understand if you need to run tests or not. If you do, then you need to install the dev dependencies too:

https://github.com/PHP-DI/PHP-DI/blob/7ab5ac6d7fc8f03ee943e386e5be666f0bd3b407/composer.json#L34-L41

> > then you have to install much more dependencies (require-dev), so that will be much harder I guess?
>
> Here is why if you remove "useless" dependencies and keep phpunit the testsuite "must" run and not throw errors.

I don't understand what you mean by "useless", these packages are required for a reason. If they are required in dev that means they are used in tests.

> I would prefer having a compatibility because all this function calls make the file less readable.

I'm not sure what you expect here?

> A foreach would not be possible to make things compatible ?

It's possible yes.

> I was thinking that DI libs where more exchangeable than what I see 🤔 ?

DI container have been standardized for get() and has(), because this is the part that is always the same. The configuration format on the other hand is what make each container unique, this is why each container exists. It's like asking each restaurant to make the same food, might as well have one big restaurant ^^

The other differentiating factor could be performance, but in 2020 all containers are way fast enough so that the difference cannot be visible.

**Comment by williamdes** [comment]
> I'm sorry, I still don't understand if you need to run tests or not.

For phpMyAdmin no.
For packaging your lib in Debian after someone uses it in their project as a dependency, yes.

> I don't understand what you mean by "useless", these packages are required for a reason. If they are required in dev that means they are used in tests.

Sure, I am pretty sure this 2 ones are not usefull for tests to run ;)
```json
     "friendsofphp/php-cs-fixer": "^2.4", 
     "phpstan/phpstan": "^0.12" 
```

> I'm not sure what you expect here?

Something more declarative like Symphony does and then run the code to make the declarations actual DI code like in your example :)

> DI container have been standardized for get() and has(), because this is the part that is always the same. The configuration format on the other hand is what make each container unique, this is why each container exists. It's like asking each restaurant to make the same food, might as well have one big restaurant ^^

I understand ;)

Give me some reflexion time and I will try an implementation ASAP

**Comment by williamdes** [comment]
Closing for now, thank you for all the support !

**Comment by williamdes** [comment]
Hi !
I am interested to have a try soon, I have read the docs and it looks like I can make it work :)

Thank you so much for the very nice support you gave on this topic !

**Comment by williamdes** [comment]
Benchmarks just got updated: https://kocsismate.github.io/php-di-container-benchmarks/benchmark.html (https://github.com/kocsismate/php-di-container-benchmarks)

I will have to run benchmarks too to make sure the numbers are right or wrong

**Comment by williamdes** [comment]
Packaging is happening for real now 😄 
Will update this issue accordingly

**Comment by williamdes** [comment]
[phpab](https://github.com/theseer/Autoload) used in Debian is unhappy:
```
Multiple declarations of trait(s), interface(s) or class(es). Could not generate autoload map.

Unit 'di\test\performancetest\get\getfixture' defined in:
 - /mnt/Dev/@debian/@pear-team/php-di/tests/PerformanceTest/get-object/GetFixture.php
 - /mnt/Dev/@debian/@pear-team/php-di/tests/PerformanceTest/get/GetFixture.php
```

What do you suggest ?

**Comment by mnapoli** [comment]
Yeah I would just skip these if I were you. Honestly I'd rather not touch these classes unnecessarily.

**Comment by williamdes** [comment]
I am closing this issue, php-di is now into Debian. I will try to run benchmarks at phpMyAdmin some day and maybe migrate to php-di to get rid of the Symfony stuff.
