### ISSUE TITLE
Convert boolean string to bolean in \DI\env

### ISSUE THREAD

**Issue by Ekimik** [PHP-DI/PHP-DI#744]
Hello,
I use environment variables to configure certain things in my Docker images, where I use php-di. Everything work great and I can get values from environment variables. But sometimes I need to configure setting, which have binary value (enabled/disabled). I use "boolean strings" to achieve this (e.g. `"true"` or `"false"`). It would be nice if those strings can be converted to proper boolean values. I found some libraries (for example [this](https://packagist.org/packages/oscarotero/env) one), which can help me with conversion, so I can live without this feature in php-di core, but it seems to me like nice feature.

What do you think about it?
Thanks for response :)

**Comment by mnapoli** [comment]
Hi,
Thanks for the details, I see what you mean.

My first reaction would be to avoid that kind of behavior, as that is not consistent with how environment variables work in Linux. `VAR=false` is a common mistake in bash/Linux, and I don't think it's up to a DI container to fix this, especially since it would mean those variables would behave differently in other languages/tools/places.

Hopefully that makes sense?

**Comment by Ekimik** [comment]
Thanks for your opinion. As I said, I can use mentioned library to achieve conversion. So it's fine for me not to add conversion to php-di. I can see your points and it's true that user should explicitelly turn on conversion rather than php-di silently convert those values. I can imagine places, where conversion is not desirable. Feel free to close this issue.

**Comment by mnapoli** [comment]
👍  thanks.
