### ISSUE TITLE
PHP-DI 6 vs PHP8

### ISSUE THREAD

**Issue by zabakala** [PHP-DI/PHP-DI#749]
Hi. Just tried to switch my app (PHP-DI 6, php-di/php-di:6.3) using **PHP7** to **PHP8**. Injections via **@Inject** ceased to work. Is it, I believe, connected to https://github.com/PHP-DI/PHP-DI/pull/726?

**Comment by mnapoli** [comment]
Hi, `@Inject` should still work in PHP-DI 7.

**Comment by zabakala** [comment]
Thx for the reply but the question is aimed at the functionality/compatibility of PHPDI v6 vs PHP8. I believe this combo is not possible due to the @Inject colission suggusted above.

**Comment by mnapoli** [comment]
Hi, I see nothing "suggested above", I don't understand. The PR you linked is PHP-DI 7, which isn't related. I don't see what the problem is, everything should work.

If something doesn't, please open a new issue with a detail on the error.

**Comment by zabakala** [comment]
I understand. Maybe improper word composition from my part. The thing is that PHP-DI v6 vs PHP8 is,  I guess, an invalid combo to use as v6 INJECT collides with php8 INJECT there. The PR provided above is the indirect question from me to verify that the only possibility to use php8 is with PHP-DI v7 only.

**Comment by SvenRtbg** [comment]
I have the feeling there is some misunderstanding going on here.

PHP-DI 6.3.1 states to be compatible with PHP >=7.2.0.
It has tests for the "annotation injection" feature: https://github.com/PHP-DI/PHP-DI/tree/master/tests/UnitTest/Annotation
And all the tests are executed using PHP 8, and do not fail: https://github.com/PHP-DI/PHP-DI/actions/runs/686178911 (later CI runs fail due to a new inspect rule coming from PHPStan).

It is safe to assume that PHP-DI 6 is working with PHP 8 in the general case.

If you have a special case where it does not work, please show your (example) code and demonstrate the issue.

@zabakala I do not know what you mean when mentioning "php8 INJECT". PHP8 does not come with any injection feature on it's own, the only thing new is that a PHP 8 annotation "#inject" is now understood by PHP-DI v7. You cannot use these annotations with PHP-DI v6.

**Comment by mnapoli** [comment]
I'll even summarize your answer because I think that's the main point 😄 :

> PHP-DI 6 is working with PHP 8
