### ISSUE TITLE
Question about php definitions, factory and static method

### ISSUE THREAD

**Issue by alexkuc** [PHP-DI/PHP-DI#752]
Hi!

In the docs, [php definitions -> factories](https://php-di.org/doc/php-definitions.html#factories), there is the following mention:

```
factory([FooFactory::class, 'build']): if build() is a static method then the object will not be created: FooFactory::build() will be called statically (as one would expect)
```

~I don't understand why this wouldn't work as:~ I don't understand why new object would not be created if the following works in vanilla php:

```php
class Test {

  public static function factory(): self
  {
    return new Test();
  }

}

var_dump(Test::factory());
```

returns `object(Test)[1]`.

Did you mean something else here?

**Comment by SvenRtbg** [comment]
Which code related to PHP-DI do you execute? What do you get? What do you expect to get instead?

**Comment by mnapoli** [comment]
Hi, yes that's exactly what happens.

What the documentation says is that:

- if `factory()` is **not** a static method, then `(new Test())->factory()` will happen
- if `factory()` is a static method, then `Test::factory()` will happen

From PHP-DI's perspective, in the second case PHP-DI is not creating an object. It doesn't really know what you do in the method.

Hope that clear things up.

**Comment by alexkuc** [comment]
> From PHP-DI's perspective, in the second case PHP-DI is not creating an object. It doesn't really know what you do in the method.

I think I got it now. In the first case, PHP-DI will create an object for you but in second case (static case), the factory is responsible for creating the object.

Did I get this right?

**Comment by mnapoli** [comment]
Exactly yes!

**Comment by alexkuc** [comment]
I would make a suggestion of *maybe* updating docs to make it more clear.

From

> factory([FooFactory::class, 'build']): if build() is a static method then the object will not be created: FooFactory::build() will be called statically (as one would expect)

To

> factory([FooFactory::class, 'build']): if build() is a static method then the factory is responsible for returning a new object (static methods cannot instantiate new objects)

If you think this is good, I can make a PR for this

**Comment by SvenRtbg** [comment]
Well, your statement is wrong: "static methods cannot instantiate new objects". That's the opposite of what is happening. The only thing that is left out is that PHP-DI does not create the object the factory method is to be called on, because it simply is not required - the static method can be called directly. And the purpose of a factory method is to return the object to be used - so any factory method has to return an object, that does not make static methods special. 

Even if PHP-DI instantiates an object, the method to be called still has to return an object. And I personally would expect such an object to be a different one than the object created for the factory call. Otherwise I would probably pull my remaining hair out to understand why there is a need for a factory call in the first place - PHP-DI would be able to create objects to be used directly, so the factory call might act as sort of an initializer call, and I would regard that as something odd.

As mentioned above, I'd really like to see your code example that you struggle with. You haven't mentioned it yet, and the result - at least from my perception - seems to be more misunderstanding.

**Comment by alexkuc** [comment]
It's really simple really - the phrasing in the docs - at least for me, gave the impression that php-di does not support static methods for factories.

Taken verbatim from docs:

> if build() is a static method then the object will not be created

**Comment by mnapoli** [comment]
@alexkuc I think you're nailing it. I think it's good to keep the beginning too, how about:

> factory([FooFactory::class, 'build']): if build() is a static method then FooFactory::build() will be called statically (the static method is responsible for returning an object or returning a value).

**Comment by alexkuc** [comment]
@mnapoli yeah, I think that's the best way to describe it

**Comment by mnapoli** [comment]
Great, feel free to send a pr

**Comment by alexkuc** [comment]
@mnapoli I have created PR #755
