### ISSUE TITLE
How do I provide a variableReader callable for the EnvironmentVariableResolver

### ISSUE THREAD

**Issue by angelxmoreno** [PHP-DI/PHP-DI#754]
Looking at the [EnvironmentVariableResolver class](https://github.com/PHP-DI/PHP-DI/blob/0ca3e76b3ce6f61f1cc2b8c881bf18f14a49e440/src/Definition/Resolver/EnvironmentVariableResolver.php#L16), I notice it has a default `variableReader` of `getenv`. Hod Do I change this?

**Comment by mnapoli** [comment]
I don't know if that's possible, what's you objective?

**Comment by angelxmoreno** [comment]
my objective is to use a thread safe method to get my env vars. `getenv` is not thread-safe and thus, vlucas/phpdotenv deprecated `putenv` : https://github.com/vlucas/phpdotenv#putenv-and-getenv

**Comment by SvenRtbg** [comment]
I'd assume reading something is always thread safe, at least if it isn't changed. It is writing to something that makes things interesting.

Are you intending to change these environment variables? How?

**Comment by mnapoli** [comment]
Then maybe the best course of action would be to change PHP-DI to use a thread safe method?

**Comment by SvenRtbg** [comment]
Well, the discussion about that feature seems to be summarized in this statement: https://github.com/vlucas/phpdotenv/issues/446#issuecomment-639016097

So to me it seems that thread-safety only applies to certain ways of running PHP (well, obviously it has to run in threads, so PHP-FPM is mentioned), then additionally the environment variables have to be different in order to "leak" between threads. If you always look at the same environment variables and also do not attempt to change it from a php script, then variable content may still leak, but you probably wouldn't notice. However, PHP-DI must not attempt to assume what the users are running their scripts on.

The alternative choice should be to access `$_SERVER`. Which probably is a good idea anyways, but I would think that this access method is already possible within PHP-DI: Just set a value, populate it with `'database.host' => $_SERVER['YOUR_DB_HOST_ENV_VAR']` and use that value where needed, instead of using the `\DI\Env` helper.

**Comment by mnapoli** [comment]
@SvenRtbg I'm not sure I understand: why shouldn't PHP-DI use `$_SERVER` instead of `getenv()` if `$_SERVER` is better?

**Comment by SvenRtbg** [comment]
Like you, I am still trying to understand the use case. However I was also suggesting an alternative to work with env vars that already works. Not intending to stop progress. :)

**Comment by mnapoli** [comment]
No worries, just wanted to make sure I'm not missing anything.

@angelxmoreno if you want, feel free to send a pull request that replaces `getenv()` with `$_SERVER` in PHP-DI.

**Comment by n00dl3** [comment]
Note that the population of superglobals like `$_SERVER` and `$_ENV` can depend on the server's configuration (`variables_order` in php.ini) :
https://www.php.net/manual/en/ini.core.php#ini.variables-order

**Comment by angelxmoreno** [comment]
PR open. Please review
