### ISSUE TITLE
Scoped injection per request

### ISSUE THREAD

**Issue by odahcam** [PHP-DI/PHP-DI#762]
The container allows values to be overriden in the request context. Values like the response, the current URI, the request itself are overriden in the container if another request comes into place and re-sets these values. 

I'm using PHP-DI with Swoole, which allows this kind of behavior, which is probably the future of PHP so I think scopes like .NET Core  are a very valid feature to be implemented. Notice that this Scope implementation would be totally different from the previous and removed version, this time Scopes are finally useful.

**Comment by SvenRtbg** [comment]
I am not sure I correctly understand your context.

My perception of DI containers is that they only provide (internally managed) singleton instances of objects, therefore are only to be used for an object graph with "eternal truth", i.e. objects with a lifespan equal to the application. Usually this means the lifetime of a single request when using a standard PHP setup (one script started per request, hosted by an external HTTP server like Apache, nginx...). And in this setup it does not really matter if the container returns "a request object" because it will only live until the request ends.

If you are building applications that intentionally live longer than a single request, then hosting request creation inside the DI container is wrong. There even is a solution proposed for that: PSR-17 describes an interface for HTTP object related factories. https://www.php-fig.org/psr/psr-17/

Such factories would be the "eternal truth", as they can emit request/response objects on demand when the application detects a request.

**Comment by odahcam** [comment]
Thanks for answering! Heres my thoughts:

> My perception of DI containers is that they only provide (internally managed) singleton instances of objects

Although this is all they could do in single-resquest-then-die-PHP, with event loop like applications this is like 1/3 of what they could or should do. 

> And in this setup it does not really matter if the container returns "a request object" because it will only live until the request ends.

Exactly, but currently there are applications that behave in a different way and they are probably the future. Their lifespan is not a request-response then die but a keep-alive application responding to requests, meaning the Singleton will be kept alive this entire time while the current behavior we have is like a Scoped service.

> [...] then hosting request creation inside the DI container is wrong.

The request is created outside the container, just some values are stored there to be used in the current request scope.

> There even is a solution proposed for that

I already implement and use this PSR, by the link you sent, I can't see how it could solve this issue. Could you elaborate on that?

---

This SO answer has a very well done explanation that helps understanding what I'm saying: https://stackoverflow.com/a/38139500/4367683

**Comment by mnapoli** [comment]
Hi, I understand.

But that's not something I want to support in PHP-DI. I encourage you to [write stateless services](https://igor.io/2013/03/31/stateless-services.html) and instead inject a `RequestHolder` service or something of the sort. This is exactly the direction Symfony took: they removed the request scope and moved to a `RequestBag` service (I think, not sure about the name).

Several times I thought about a container with sub-scopes (i.e. sub-containers that are instantiated for the time of the request only, with all its object graph) and I think it's doable, but I'm not sure if:

- it's worth the effort
- it will have a positive impact on the codebase (I anticipate a nightmare of mixing different scopes, which was the case in Symfony before)

Anyway, that's why I don't want to implement that in PHP-DI :)

**Comment by odahcam** [comment]
I understand. Now after some time to think about it, I would only need the Request to be available in the presentation layer, thus in the containers, middlewares and templates. The only last thing that I'm dependent on is the currently authenticated user, which I'm pretty sure can be injected once in the app's controllers via constructor arguments and passed down the dependency three as a parameter. This would in fact make the application more reliable and stable. But for the templates the issue remains as I would have to change lots of things to make it work.

I'm divided now by working in the container or the application. I was interested before in creating a PR here, but as @mnapoli said it won't be a feature in PHP-DI, so do you now any other containers or frameworks which implement this lifecycle/scope feature?

**Comment by odahcam** [comment]
I understand. Now after some time to think about it, I would only need the Request to be available in the presentation layer, thus in the containers, middlewares and templates. The only last thing that I'm dependent on is the currently authenticated user, which I'm pretty sure can be injected once in the app's controllers via constructor arguments and passed down the dependency three as a parameter. This would in fact make the application more reliable and stable. But for the templates the issue remains as I would have to change lots of things to make it work.

I'm divided now by working in the container or the application. I was interested before in creating a PR here, but as @mnapoli said it won't be a feature in PHP-DI, so do you now any other containers or frameworks which implement this lifecycle/scope feature?

**Comment by mnapoli** [comment]
I would recommend to have a look at Symfony and there RequestStack service to move away from that pattern.

Basically you have a service that has a `getUser()` (or `getRequest()`) method. Instead of injecting the request, you inject that service. And whenever the request/user changes, then the service should return the new instance.

**Comment by SvenRtbg** [comment]
Fun fact: If you google for "php scope DI", you'll end up at results detailing that scopes have been removed from PHP-DI in an earlier version.

**Comment by odahcam** [comment]
@SvenRtbg aaaand that's how I got here, hehe. Thanks guys.

**Comment by odahcam** [comment]
Hey guys, sorry to bother again, but I have a related question. Would it be possible to have multiple containers in a single application and for each request instantiate the application through a different container? I'm afraid things like autowiring and inject annotations would crash. I know it seems very strange at first, but I'm trying to migrate an classic single threaded, Nginx + PHP-FPM application to an event loop server, and this "request scoping" through different containers would mimic the current behavior the container has in the PHP-FPM environment, working as a temporary quick step in the application redesign. I would then move away from that implementation in favor of refactoring the application for better design.

**Comment by odahcam** [comment]
Lifecycle, documentation and workarounds should be a concern with the ecosystem of async PHP growing with Laravel Octane, RoadRunner, Swoole, etc.

**Comment by mnapoli** [comment]
Even in long-running processes, I'm still of the opinion that services should be stateless. The request should never be injected because it contains state.

Take a look at my link about about the "RequestStack" service in Symfony: this is the right approach.

Or maybe I'm misunderstanding what you are asking.

**Comment by zabakala** [comment]
I think it is not related to the request object only. If we are inside an event-loop driven application, all services keep their state across individual requests which does not happen in a standard request-and-die app. We either have to define some kind of flush mechanism to reset such a service as it now retains its state from the previous loop (i.e. event-loop app with a service injected via @Inject annotation or a constructor) or, maybe, have a way to autowire a service with some kind of symptom saying that it should be reset for another loop or somehow provide another untouched container for another loop.

**Comment by mnapoli** [comment]
Could you give examples of services that need to be reset, and why?

**Comment by zabakala** [comment]
As far as possible examples go, let's stick again to the already mentioned Octane as it provides some use-cases https://divinglaravel.com/laravel-octane-bootstrapping-the-application-and-handling-requests

**Comment by mnapoli** [comment]
That article did not provide anything useful to our discussion here, maybe I missed it (I know Octane so I skimmed the article).

**Comment by SvenRtbg** [comment]
That article specifically discusses the problem with mutating the configuration object (setting a different AWS key as an example), and later states that Octane tries to keep these mutations at bay, but inevitably cannot probably prevent bad third party software from mutating itself, affecting the unexpected use case of persistent PHP request processing.

I think the core of our discussion is to find reasons why it would be a good idea to offload service instantiation for things that are per request to a central DI container instead of only using this container for application-level lifetime, and offloading instantiation of request-level objects to dedicated factories (which in turn could avoid hosting state and be injected by the DI container itself).

I think it might boil down to the PHP-DI maintainers evaluation of what kind of solution is most likely to be established in the PHP world. Numerous efforts have been established inside PHP core to improve performance by adding all kinds of persistent caches (opcache, preloading, JIT, and probably more), all of which do not touch the shared-nothing architecture of request handling. The efforts to establish something like a PHP application server however are currently userland scripting only, with no engine powered solution in sight. That might just be the hint that a minority is able to code cool stuff, but there isn't any real demand from the majority.

**Comment by odahcam** [comment]
>  and offloading instantiation of request-level objects to dedicated factories (which in turn could avoid hosting state and be injected by the DI container itself)

My main struggle is that I couldn't see a way to make this work in some automated way. While using this container with an injector is pretty straight forward and most apps already uses this pattern, that factory pattern you mentioned doesn't seem very obvious to me.

Can I imagine an implementation with factories and instantiation per request of my needs? Yes.
Do I like what I imagine? Kinda not.
Why I don't like it? Because Me and my team would need to re-write lots of code to make something like that to work and we would lose sugars we already have.

At this point, I kinda agree with the author's opinions, but it would be nice to have maybe an abstraction so we could combine multiple containers and use them for injection to mimic scopes like .NET Code does, just because it would make devs lives easier to understand.
