### ISSUE TITLE
PHP 8 union types?

### ISSUE THREAD

**Issue by mindplay-dk** [PHP-DI/PHP-DI#767]
Hey @mnapoli 🙋‍♂️

Any plans to support PHP 8 union types?

Asking as one fellow IOC container maintainer to another. 😊

As a developer, one would almost naturally expect to be able to inject against a constructor parameter that accepts two different types, but it's less obvious how someone would expect this to *work*.

I've seen IOC containers in the C# space that support method overloading, and frankly this stuff is so complex, unreliable and unpredictable, I wouldn't even want this feature in a C# container at all.

In PHP, this basic form of overloading with alternative types in a method signature, at least there's only one method implementation, so at least you know what the user is trying to call - but many of the other problems are still present, I'm afraid.

For starters, the absolute simplest case, where you have a constructor like `__construct(A|B $foo)`, and you've configured two services `A` and `B`, which type do you expect would be injected against `A|B $foo`? There's no right answer, is there?

IOC containers in the C# space popularly come up with answers to questions like these, and usually it's something along the lines of "fingers crossed, just do *something*" - which makes for a really unpredictable experience with tools like these, where some seemingly harmless refactoring leads to *something* getting injected, and I find myself wishing they would just throw an exception rather than attempting to resolve these.

In PHP, this difference is even more temptingly simple on the surface - just changing `A` to `A|B` seems like a simple change, and it's not totally obvious how radically different these type-hints really are.

I'm leaning towards doing nothing - or possibly throwing an exception, forcing the developer to hand-write a factory-function with explicit types that can be predictably resolved.

Is this along the lines of your rationale as well, or do you have something planned? 🤷‍♂️

**Comment by mnapoli** [comment]
Hey!

Yeah, unless there is something obvious that should happen (and isn't currently implemented in PHP-DI right now), I have no plan on adding any behavior TBH.

As you said, no idea what to do with `A|B $foo`.

**Comment by SvenRtbg** [comment]
Adding the view of the user: PHP-DI has autowiring and made it perfectly clear that it can only apply it if the choice is unique. Anything else has to be defined somewhere, with the most obvious example being interfaces.

The interesting question would be how to express a definition for such a union type. Two possible solutions would come to mind: 
a) Require a constructor parameter definition for the class requiring a union type. Defining factory closures or anything like that. I.e. have code that actively builds the class and decides about that union type dependency.
b) Sort of autowire it because there is an explicit definition for `A|B` being made, just like an interface.

You could also imagine a hybrid scenario like `A` is explicitly defined, so use `A` then, never `B`, but I think this will quickly lead to madness.

So in any case, my defining factor about PHP-DI is that it can be trusted to do the right thing because there is no choice when autowiring, otherwise I as the developer have to step in and provide a definition because only I know how to solve ambiguous definitions.

**Comment by mindplay-dk** [comment]
> So in any case, my defining factor about PHP-DI is that it can be trusted to do the right thing because there is no choice when autowiring, otherwise I as the developer have to step in and provide a definition because only I know how to solve ambiguous definitions.

This is really clear cut 🙂

Thank you both for the discussion - I'm closing the issue.

**Comment by mindplay-dk** [comment]
@mnapoli btw, did you intentionally block me on Twitter? wondering if I said something offensive 😔

**Comment by mnapoli** [comment]
Hey @mindplay-dk, I just checked and yes indeed 😅 
I think it goes back several years ago, maybe something related to PSR-11 or other controversial topics at the time, one discussion too many. Anyway, thanks for the ping, just removed that, let's move forward.
