### ISSUE TITLE
Roadmap for incorporating PHP 8.0 features

### ISSUE THREAD

**Issue by vasily-kartashov** [PHP-DI/PHP-DI#779]
Is there a roadmap the project leads could share with us, telling us where this project is going and what to expect next? 

I am particularly interested in using attributes for autowiring, in line with what Spring Framework is doing. #[Component], #[Configuration], #[Environment], #[Profile] etc.

**Comment by SvenRtbg** [comment]
There is the milestone for the next major release: https://github.com/PHP-DI/PHP-DI/milestone/22

The open PR #726 description states that `#Inject` will be available in PHP8 code instead of requiring the `@Inject` annotation. And that's about it as far as I know. But it might be used inline to automatically inject parameters into constructors, for example.

There are already 3 beta versions being released. You might just want to check them out.

**Comment by mnapoli** [comment]
Yes, feedback on beta version of v7 is very welcome. Check out #726 for more details. Thank you @SvenRtbg for all the links and details!

**Comment by vasily-kartashov** [comment]
I am gathering the requirements, but at the very least I'd like to be able to say something like
```
#[Configuration]
class MyConfiguration
{
    #[Bean]
    public function database(#[Env("hostname")] string $hostname, ...): Database 
    {
        ...
    }
}

#[Profile("production")]
class MyProductionConfiguration 
{
    #[Bean]
    public function myService(): MyService {}
}
```

**Comment by SvenRtbg** [comment]
Can you also explain what should happen with these annotations? I'm not used to anything Java. :-P

**Comment by vasily-kartashov** [comment]
`#Configuration` annotates classs containing bean definitions. 
`#Bean` will annotate either bean classes or bean factory methods.
`#Env` autowires `get_cfg_var` without explicitly fetching it.
`#Profile` creates context for bean definitions thus letting us using different bean definitions in different environments.

So basically having a couple of classes somewhere

```
#[Configuration]
class ApplicationConfiguration
{
    #[Bean]
    public function database(#[Env("hostname")] string $hostname, ...): Database 
    {
        ...
    }
}

#[Bean]
class MyService
{
     #[Inject]
     public function __construct(private Database $database) {}
}
```


and running:

```
$container = Container::scan($namespace, $profile);
$container->get(MyService::class); 
```

should be enough to assemble the corresponding DI graph and return the node of type `MyService`. 

The devil is obviously in details :) Happy to elaborate further but I need to know if you guys are interested in moving the project in that direction at all.

**Comment by mnapoli** [comment]
@vasily-kartashov I'm sorry but this is nowhere close to how PHP-DI works. I don't see a case for drastically changing the project's architecture and API.

**Comment by SvenRtbg** [comment]
I hope nobody minds if I go a bit more into details why I think rejecting the request is ok:

First, PHP does not really care about Beans. You can create classes with getter/setter methods. All classes are serializable by default, special cases can be handled by magic methods. So I don't think #Bean can do something useful. I may misunderstand beans, but I think they solve a problem PHP doesn't have.

#Configuration is weird. PHP-DI should be the place to put creation code into. If you put an annotation somewhere to signal "hey, I can build class X", this has to be found in order to be called. PHP annotations are passive, they are not actively registered somewhere. So you'd have to scan the whole codebase for them - not great for performance.

#Profile or something with the idea of environment specific setup has been proposed recently, but my view on this is it is better handled during bootstrap runtime. IIRC that proposal wasn't successful.

The only thing remaining is #Env, but as a standalone option it's fairly useless, and PHP-DI already offers something like this for its existing configuration DSL. You can even use the #Inject annotation to fetch a config value. On the other hand coupling code with a DI framework is not always a good idea, but YMMV.

**Comment by vasily-kartashov** [comment]
This is helpful, thank you. There's a couple of things that I think I need to elaborate on because it seems to me this is a discussion about terminology and not substance.

Beans are not much different from what you call definitions: https://php-di.org/doc/php-definitions.html Basically a named node in the DI graph, that is most often identified by its type (that's where profiles are useful). The only difference is that #[Bean] marked function is pure PHP and as such can be analysed by developers, static analysers and IDEs just fine. compare

```
[
    Database::class => DI\factory(function (ContainerInterface $c) {
        return new Foo($c->get('db.host'));
    })
]

#[Bean]
public function foo(#[Env("db.host")] string $host): Foo {
    return new Foo($host);
}
```

`Configuration` is the way to mark classes containing bean definitions. It certainly is faster to manually provide these definitions to the container, but the idea is the same

```
$containerBuilder->addDefinitions('config.php');

$containerBuilder->addConfigurations(MyConfiguration::class);
```

`Profile`, and `Env` allow you to assemble 2 graphs, almost identical where just a few nodes alternate between different implementations (like different DB type on develop vs production, but both of the same type `Database`). `Profile` is almost an equivalent to what you call environment: https://php-di.org/doc/environments.html

Just to stress my point: the main advantage of annotations is that the whole code is still good old PHP functions/objects. The annotations here don't try and solve some fancy issues you are unaware of.
