### ISSUE TITLE
Why not use psr/container v2?

### ISSUE THREAD

**Issue by iRaziul** [PHP-DI/PHP-DI#789]
I was using php-di with Slim v4 but while installing I've noticed that It was asking for psr/container 1.x and for that I had to use -W flag and downgraded psr/container to 1.x.

But the question raises there that why php-di is not adopting psr/container v2?

**Comment by SvenRtbg** [comment]
There is very little difference between the two versions. Essentially only the `has()` method got a return type of `bool`.

And additionally, because other parts of a project might be forced to version 1 due to other dependencies, PHP-DI would have to support both variants. Not impossible, though. You might even send a pull request for this small change.

**Comment by nbayramberdiyev** [comment]
Done in https://github.com/PHP-DI/PHP-DI/pull/726.

**Comment by geek-merlin** [comment]
Same prob here. #726  is still unmerged unfortunately.
