### ISSUE TITLE
How can factory supply many instances when using DI Container with constructor injection

### ISSUE THREAD

**Issue by alexkuc** [PHP-DI/PHP-DI#807]
I am trying to figure out how to write a PHP factory that uses constructor injection via dependency container (DI) that can create _many_ objects.

This is boilerplate code for the factory:

```php
<?php

interface ItemInterface
{
}

enum ItemType: string
{
  case ItemA = ItemA::class;
  case ItemB = ItemB::class;
}

class ItemA implements ItemInterface
{
}

class ItemB implements ItemInterface
{
}

class ItemFactory
{
  protected function __construct()
  {
    // static factory, prevent new instances
  }

  public static function make(ItemType $type): ItemInterface
  {
    return new $type->value();
  }
}
```

```php
class LogicForItemA
{
  // $item is resolved to ItemA via DI Container and constructor injection
  public function __construct(
    protected ItemInterface $item
  ) {
  }
}
```

When we want to create a _single_ instance of either `Item A` or `Item B`, it seems straight forward to me:
- type hint against interface to avoid tight coupling
- use DI Container to inject concrete instance via constructor injection
- this is configured in DI Container config to avoid calling container directly
- all external dependencies are clearly outlined in the constructor

When we want to have multiple instances of either `Item A` or `Item B`, I am not sure how to implement it properly. Here's what I made:

```php
class LogicForManyItems
{
  public function __construct(
    protected ItemFactory $factory
  ) {
  }

  public function doLogic()
  {
    $item1 = $this->factory->make(ItemType::ItemA);
    $item2 = $this->factory->make(ItemType::ItemA);
    $item3 = $this->factory->make(ItemType::ItemA);
  }
}
```

However, this doesn't feel right. My concerns are the following:
- it "feels" like `doLogic()` is now tightly coupled with `Item A`
- dependency on `Item A` is now missing from constructor
- instantiation of `Item A` is now "buried" inside method (not even function parameter)
- with lots of code it will become obscured

There are legitimate reasons to have a need for many instances of another class but I am not sure how to implement it cleanly or properly when using factory with DI Container that does constructor injection.

**Comment by SvenRtbg** [comment]
It might be I am missing the core of your question entirely...

I understand there are situations where multiple instances are required. The usual case is when different values are encapsulated into the same class - they have to be implemented using multiple objects during runtime.

The easiest and most obvious way to implement multiple instances is unsurprisingly:

    $item = new ItemA();

And yes, this is tightly coupled and will always return ItemA instances.

A more generic approach would be:
  
    $item = clone $this->itemTemplate;

If you inject the initial instance of an `ItemInterface` into the factory and then clone new, independent item instances, you can change the implementation class. The only problem here might be inside any item object may be hidden multiple layers of other objects that you'd also like to clone, but "clone" isn't working recursively, you'd have to code it yourself or use a library for that. I'm not discussing right now if this is the correct approach (my answer would be "no" if the item is for example a database result, and it contains the database connection internally, it would be "yes, of course" if more detailed item objects would be included and have to be cloned).

Something that I would question is: How is this all connected to PHP-DI? I'd believe this is quite out of scope, because if you require multiple object instances, you are possibly quite deep inside the business logic where it is necessary to couple code to concrete implementations, so executing `new` has to be done in some way or another to get one or more instances. And even `clone` isn't some very different approach, it is basically the same thing as running `new $classname`, but using an object instead of a string. And if you don't like `clone`, but also want to be dynamic, `$class = get_class($template); new $class()`.

Should PHP-DI play a role in this? Probably not. Of course you could pull new instances from it, but you are already aware that tight coupling to implementations is bad. Calling `$phpdi->make($class)` would be such a tight coupling.

One thing that your example is currently not explaining at all is why you'd need a generic approach for multiple items sharing the same interface - or multiple possible implementations that may be changed for one another. "Item" is too generic to have any reasoning about it. So either I am misunderstanding what you want to do, or you intend to do something that has a way better solution from the start, and you already stepped in the wrong direction and are now asking detailed questions about your intended solution, but should really ask about the underlying problem. Maybe adding some more context would help.

**Comment by defunctl** [comment]
I think what @alexkuc is talking about here is utilizing something like the [Strategy Design Pattern](https://refactoring.guru/design-patterns/strategy). 

I also think PHP-DI would benefit from contextual bindings, for example like [Laravel's Service Container offers](https://laravel.com/docs/9.x/container#contextual-binding) to make patterns like this easy to implement.

**Comment by alexkuc** [comment]
@defunctl yes, I am referring to strategy pattern here.

@SvenRtbg I'll simply my question.

I am implementing a [static factory pattern](https://designpatternsphp.readthedocs.io/en/latest/Creational/StaticFactory/README.html) with _variable_ number of classes to be created by the factory. Something like this:

```php
ItemFactory:make(Item::ItemA, 5)
```

which would return an array of 5 `ItemA` instances. Instead of using `clone` or calling DI directly, I was thinking that _maybe_ we could achieve this somehow using dependency injection via constructor.

As far as I can tell, this is _not_ feasible, right?

**Comment by mnapoli** [comment]
@alexkuc yes AFAICT that's not a feature of PHP-DI.

**Comment by alexkuc** [comment]
@mnapoli Thank you for confirming that. I'll close the issue then.
