### ISSUE TITLE
Why when changing the value of a dependency of an object, the dependency of another object of the same class also changes?

### ISSUE THREAD

**Issue by chaungoclong** [PHP-DI/PHP-DI#832]
**I created 2 objects of class B. I don't understand why the dependency `a` of the two objects is the same. 
When I change the `name` property of the `a` dependency of one object, the other object's `a` dependency also changes.
I tried with illuminate/container and it doesn't happen like that**
"sorry about my english"
```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use DI\ContainerBuilder;

try {
    $c = (new ContainerBuilder())->build();

    // Create 2 objects of class B
    $b1 = $c->make(B::class);
    $b2 = $c->make(B::class);

    var_dump(
        $b1 === $b2,       // bool(false)
        $b1->a === $b2->a, // bool(true): Why is the dependency A of 2 objects B is the same?
        $b1->a->name,      // string(7) "default"
        $b2->a->name       // string(7) "default"
    );

    $b1->a->name = 'changed';

    var_dump(
        $b1 === $b2,       // bool(false)
        $b1->a === $b2->a, // bool(true)
        $b1->a->name,      // string(7) "changed"
        $b2->a->name       // string(7) "changed"
    );
} catch (Exception $e) {
    echo "Error: " . $e->getMessage();
}

class A
{
    public string $name;

    public function __construct(string $name = 'default')
    {
        $this->name = $name;
    }
}

class B
{
    public A $a;

    public function __construct(A $a)
    {
        $this->a = $a;
    }
}

```

**Comment by SvenRtbg** [comment]
PHP-DI usually only creates one instance per class and reuses that instance whenever asked for it. This would be quite obvious if you`d use `$c->get(B::class)`, because that probably is the default way to fetch objects from the container (i.e. `make()` is not part of the container interface PSR). Or put another way: If you have to get new instances of objects all the time, the task of creating them may not be something the container should do.

If you want to continue with the container, you may want to provide a factory function for creating `B` which explicitly calls `make(A::class)` inside.
