### ISSUE TITLE
7.x IDE Integration broken?

### ISSUE THREAD

**Issue by Gounlaf** [PHP-DI/PHP-DI#844]
Hi :wave:,

I'm doing some tests with version 7.x before using it more globally.
I was using the [.phpstorm.meta.php trick](https://php-di.org/doc/ide-integration.html#metadata-file) to help PhpStorm resolving correctly the classes fetch via container. It doesn't work anymore.

I see that PhpDoc has changed, and, If i'm correct, it uses now [psalm](https://psalm.dev)?

```php
    /**
     * Build and return a container.
     *
     * @return ContainerClass
     */
    public function build()
```

I'm using this trick right now.

```php
/** @var Container $container */
$container = $containerBuilder->build();
```

Is it a "misuses" of psalm from PHP-DI side, or a bug I will report to PhpStorm?

Thanks.

Regards.

**Comment by mnapoli** [comment]
Thanks, this might be a side effect of #842 

@hemberger any idea?

Supporting PhpStorm is for me important, so we can always roll back #842 if we don't have an alternate solution.

**Comment by hemberger** [comment]
Support in PhpStorm for inferring class template types from the constructor was added in version 2021.3 (see https://blog.jetbrains.com/phpstorm/2021/12/phpstorm-2021-3-release/#infer_generic_types_from_constructor). What version are you using?

If we need to support versions of PhpStorm prior to 2021.3, I can work on a patch to fall back to the old return types for older PhpStorm users. This fallback will, of course, not work properly unless using the default `Container` class (since that's what #842 fixes).

**Comment by mnapoli** [comment]
Thanks for the update! 2021.3 is old enough, so unless there's a bug somewhere we should be good.

@Gounlaf can you confirm your PhpStorm version?

**Comment by Gounlaf** [comment]
@mnapoli I'm using the last stable version

**Comment by hemberger** [comment]
@Gounlaf Thanks for the info. It looks like inferring template types from the constructor works properly _unless_ the type is given as a `class-string<T>` instead of just `T`, which it is here. There is a support ticket for this, and they're slowly churning through their backlog of generics features: https://youtrack.jetbrains.com/issue/WI-65811/Infer-type-from-constructors-class-string-parameter

@mnapoli Would you like me to submit a PR for this? Basically, I'd be reverting to the non-templated types, but adding PHPStan/Psalm-specific template annotations. It's a shame that PhpStorm support is lagging behind.

**Comment by Gounlaf** [comment]
IMO You shouldn't "fix" something that is not broken. It's on PHPStorm side... not yours :man_shrugging:

**Comment by mnapoli** [comment]
@hemberger yes a PR would be great until it is fixed in PhpStorm.

(To better explain my POV, we care about the user experience, regardless of "who's fault it is". So if PhpStorm is not ready, we should find solutions so that users of PHP-DI are not impacted)
